ergochat/ergo

Makefile, README.md
This would help me (and others doing clone and/or builds from source) - so only some target systems can be built.
In theory this would replace the `build.sh` script but I didn't want to drop that if you wanted to still use it short term. I did my best to run both `build.sh` and `make` and compare directory outputs and nothing looked amiss from that (for what it is worth).
=> Makefile for os-specific builds

irc/config.go, irc/strings.go, irc/strings_test.go, web/config.go
This matches the behavior of inspircd at the very least.
Previously, the comment above that section claimed ':' should be
disallowed, but the code didn't do so.
I also simplified the code a little bit and added tests.
=> strings: disallow ':' in nicks

irc/net.go
PTR records ending in `.` (e.g., `google-public-dns-b.google.com.`) were considered invalid and therefore the IP address was displayed instead of the hostname. This trims the trailing period.
I think this broke in 5e72409695d34d1b9cd5bfdfa0a22e698effe030 ?
=> fix hostmask issue

.gitignore, irc/channel.go, irc/config.go, irc/modes.go, irc/modes_test.go, irc/server.go, oragono.yaml
Thanks for the pointers!
This should be backwards-compatible: if the line is not present in the config, it should default to `+nt`.
=> implement #132 (configurable default channel modes)

irc/config.go, irc/server.go
There are a lot of changes here and it's all kind of fiddly, so a careful review would be much appreciated :-)
Here's an overview of the changes:
1. `server.listeners` is now read and written only from `createServer` and `rehash`, not from the listener goroutine. This fixes the crash from #134.
1. I've given up on getting the API to provide a reasonable guarantee of when addresses are safe to rebind to (golang/go#21833). Therefore, the operation of updating a listener no longer stops the existing listener; instead, `rehash()` modifies the listener's `*tls.Config` in place, protected by a mutex. These updates are then picked up every time the listener accepts a connection. (I'm relying on the assumption that uncontended lock acquisition on modern systems is generally fast.) The same …
=> refactor create/update/destroy of listeners

irc/client.go, irc/getters.go, irc/monitor.go, irc/nickname.go, irc/server.go
This rewrites most of the `/monitor` implementation. It's mostly about simplifying the lock model: rather than separate monitoring mutexes on both the client and server, the data is centralized in a `MonitorManager` struct with its own `sync.RWMutex`. It does fix at least one unsynchronized map access; the technique [here](https://github.com/oragono/oragono/blob/5e9767c46db37fc2cd69ecc1d2040883f92f923e/irc/monitor.go#L216) does not work correctly, since copying a map by assignment only produces a shallow copy.
The monitor implementation should be generally free of read-write races now, since it accesses all client state via getter methods protected by the new mutex `Client.stateMutex` (analogous to `Server.configurableStateMutex`).
I changed some wire behavior, in particular:
1. Sending …
=> refactor monitor and /oper implementations

irc/client.go, oragono.yaml
* Lower ident timeout to 1.5 seconds, as discussed in #oragono
* Enforce connection limits at the granularity of ipv4 /32's and ipv6 /64's
* Raise the limit on number of new connections to 64 every 10 minutes
(for the benefit of people behind large IPv4 NATs)
=> tweak some defaults

irc/client.go, irc/commands.go, irc/gateways.go, irc/getters.go, irc/idletimer.go, irc/server.go
A few different things happening (hopefully mostly separated by commits):
1. Eliminate `Client.quitMutex` and `Client.destroyMutex` in favor of `stateMutex`
1. Eliminate `Client.timerMutex` and the whole timer setup, which didn't work correctly (instead falling back to the TCP implementation's timeouts). This breaks out the timeout setup into a separate type that implements a state machine. (The state machine doesn't use `time.Timer` because `Timer.Reset()` apparently has [esoteric race conditions](https://golang.org/pkg/time/#Timer.Reset) requiring client workarounds.)
1. Code outside the core `Server` implementation shouldn't acquire `configurableStateMutex` (a tier 1 mutex) on its own; rather, it should defer to getters.
There are a lot of potential edge cases in the timeout stuff. …
=> eliminate all Client mutexes other than stateMutex

irc/channel.go, irc/chanserv.go, irc/client.go, irc/client_lookup_set.go, irc/getters.go, irc/modes.go, irc/roleplay.go, irc/server.go, irc/types.go
This eliminates `Channel.membersMutex` in favor of a finer-grained (tier 1) mutex, `Channel.stateMutex`. Lots of moving parts, unfortunately.
`Channel.Members()` returns a cached slice of the current channel members. This allows code external to `Channel` to iterate over the members without holding any locks. Normally, this would raise a concern about turning O(1) map writes into O(n) operations, but in this context, we send O(n) messages to the preexisting/remaining channel members after any join or part, so it's fine.
=> refactor synchronization for Channel

irc/client.go, irc/config.go, irc/getters.go, irc/server.go, oragono.yaml
I accidentally wrote an edge case with a nil dereference over on #155. Then I fixed it, but it seems like we can mostly just work around them using the `recover()` function.
To test this change, I reverted 2791476f16634ae664fbd86a946de09fe1f7fa9b and triggered the underlying crash. The following output was logged (the first line via the logging mechanism, and the rest to stderr directly): https://gist.github.com/slingamn/661b326b5b0cafca36fcb8cb7e4dde17
Other clients, and the overall server state, were not disrupted.
Any concerns about logging private data? It's vaguely possible that something private could be in the string value of the panic itself, but the stack trace seems fine to me.
=> recover from client-caused panics

irc/channel.go, irc/channelmanager.go, irc/client.go, irc/getters.go, irc/monitor.go, irc/server.go, irc/types.go
This splits out channel name synchronization into a separate `ChannelManager` type protected by a tier-2 mutex, removing `channelJoinPartMutex`.
My Hexchat install doesn't correctly interpret Oragono's `/rename` responses (it gets the JOIN and PART messages, but it doesn't correctly display the WHO list or attempt to read the topic). I'm guessing some of this is Hexchat's fault? Anyway, this branch doesn't change the behavior there AFAICT, it's just something we might want to look into later.
=> remove channelJoinPartMutex

irc/channel.go, irc/channelmanager.go, irc/client.go, irc/getters.go, irc/modes.go, irc/monitor.go, irc/nickname.go, irc/server.go
"Effective Go" says getters shouldn't start with "get":
https://golang.org/doc/effective_go.html#Getters
I've been inconsistent about this so I thought I'd fix it up in between branches.
=> rename some getters

irc/channel.go, irc/channelmanager.go, irc/channelreg.go, irc/chanserv.go, irc/getters.go, irc/modes.go, irc/server.go
This moves channel registration to an eventual consistency model, where the in-memory datastructures (Channel and ChannelManager) are the exclusive source of truth about the current state of the world, and updates to them get persisted asynchronously to the DB. None of the actual components know about buntdb directly; instead, there's a `ChannelRegistry` struct that exposes load, store, and rename methods.
The eventual consistency rationale is the same as on #160. Suppose we have two concurrent updates to the topic (for example). Those updates are linearly ordered by `Channel.stateMutex`. Each update triggers an asynchronous update of the persistence layer, where we acquire a lock (`ChannelRegistry.Lock()`), read a snapshot of the channel state, persist it to the DB, and release the lock. …
=> remove registeredChannelsMutex

irc/channelmanager.go
I introduced this in #157. This is pretty bad; I originally triggered it with `/mode #nonexistent_channel b`. On the other hand, the error recovery code from #156 successfully mitigates --- you just get disconnected instead of crashing the server.
This is another good candidate for an irctest test.
=> fix a wide-ranging assortment of crash bugs

irc/client_lookup_set.go, irc/modes.go
Fixes #163. Freenode allows unprivileged listing of `b`, but not `e` or `i`. Beats me why.
In #155, I introduced a bug where removing a ban didn't cause recompilation of the ban regex. This fixes that.
=> allow non-operators to list bans

DEVELOPING.md, README.md, irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/dline.go, irc/idletimer.go, irc/kline.go, irc/monitor.go, irc/nickname.go, irc/server.go, irc/snomanager.go, irc/whowas.go
This should finish #152. Anyway:
1. This allows capitalization-only nickname changes (they were previously ignored)
1. `ClientManager` now synchronizes `Client.nick` with the casefolded nickname the server is using to track the client. This is probably unnecessary.
=> refactor ClientManager

irc/client.go, irc/idletimer.go
squigz on freenode reported an issue where bots were responding to PING
on time, but were occasionally being timed out regardless. This was a race
condition: timeout was detected as idleTime >= it.quitTimeout, but if
the client responded promptly to its PING message and sent no further messages,
but the main loop subsequently slept for longer than expected (i.e., significantly
longer than quitTimeout), this condition would be met through no fault of the
client's.
The fix here is to explicitly track the last time the ping was sent, then test
!lastSeen.After(lastPinged) instead (making use of time.Time's monotonicity).
It is sufficient that the measurement of lastPinged happens-before the PING is sent.
=> fix a race condition in client timeouts

irc/channelreg.go, irc/commands.go, irc/server.go
This removes `Server.commands` (unused), `ChannelRegistry.channels` (unused), and `Server.newConns` (unnecessary, since we may as well just hand new connections off to new goroutines directly).
This last change introduced an initialization loop:
````
./commands.go:56:5: initialization loop:
/home/shivaram/go/src/github.com/oragono/oragono/irc/commands.go:56:5 Commands refers to
/home/shivaram/go/src/github.com/oragono/oragono/irc/server.go:1615:75 rehashHandler refers to
/home/shivaram/go/src/github.com/oragono/oragono/irc/server.go:1192:6 (*Server).rehash refers to
/home/shivaram/go/src/github.com/oragono/oragono/irc/server.go:1214:6 (*Server).applyConfig refers to
/home/shivaram/go/src/github.com/oragono/oragono/irc/server.go:1546:6 (*Server).setupListeners refers to …
```
=> remove some unused members

irc/gateways.go, irc/utils/net.go
Fixes the following issues:
1. There was a quirk where you could connect through a gateway that passes `PROXY` as the first command, then pass `WEBIRC` manually. Since `client.socket.conn.RemoteAddr()` would be something like `127.0.0.1` during processing of the `WEBIRC` command, this would allow you to bypass host checking for `WEBIRC`. (You'd still have to know the password, though.)
1.  `WEBIRC` would not set the TLS flag on the connection if the last hop (from the gateway to oragono) was plaintext, even if it was on a secure connection like loopback.
1. Kiwi's [gateway](https://github.com/kiwiirc/webircgateway/blob/457c708adc51a5fe83fead2aa1ce53f9f1e0e20e/pkg/webircgateway/clientKiwiirc.go#L56) sends the flag `secure` instead of `tls` to indicate a secure connection. (Is there a spec …
=> tweaks to webirc functionality

irc/client.go, irc/gateways.go, irc/server.go, irc/utils/net.go, oragono.yaml
This change:
1. adds a fair amount of implementation complexity
1. is very silly
1. is (I think) kind of awesome
Some behavior changes:
1. You can no longer specify hostnames (other than `localhost`) as allowed for PROXY or WEBIRC. (This avoids trusting the DNS.)
1. You can now specify CIDRs instead.
1. To allow PROXY or WEBIRC from a UNIX domain socket, add `localhost` to the relevant allowed-hosts section of the config.
1. In the rare edge cases where a client may be connected via UNIX domain socket without having (yet) issued PROXY or WEBIRC, we pretend its IP address is `127.0.0.1` for the purpose of hostmasks etc.
=> support unix domain sockets (#184)

irc/accounts.go, irc/client_lookup_set.go, irc/config.go, irc/idletimer.go, irc/nickname.go, irc/server.go, oragono.yaml
* Clients are now renamed, not disconnected, on reservation timeout
* Nick reservation config is now its own subsection
=> changes to nick reservation

irc/server.go
Go v1.10 is out, including the release of our listener-closing proposal! We can now dispense with `stopEvent`.
=> clean up stopEvent (requires go v1.10)

irc/connection_limits/limiter.go, irc/handlers.go, oragono.yaml
1. `ips-per-subnet` is a confusing name; this renames it to `connections-per-subnet` while preserving backwards compatibility.
1. Add a warning to the reference config file about whitelisting `WEBIRC` gateways from the limiter and throttler.
1. Make `NAMES` behavior complaint with the RFC. (This removes the operator check, since even before this, unprivileged users could issue bare `NAMES` and see all the channels. This should probably end up being a role capability --- does the role capability system support assigning privileges to non-operators?)
=> some small fixes

irc/client.go, irc/config.go, irc/getters.go, irc/handlers.go, irc/nickname.go, irc/server.go, oragono.yaml
Implements what we talked about, more or less: you can send `NICK` and `USER` before `PASS`, but by the time registration is complete (i.e., you sent `NICK` *and* `USER`, and also` CAP END` if you're doing negotiation), you must have sent `PASS` (or authenticated with SASL, if the server is configured to accept that as an alternative).
The tradeoff is that you don't get your nickname error, e.g., `ERR_NICKNAMEINUSE` or `ERR_ERRONEUSNICKNAME`, until the final registration command (probably either `USER` or `CAP END`). But I'm guessing most clients can tolerate this OK. (Hexchat correctly switches over to the second-choice nickname, at which point it sends a new `NICK` command and registration succeeds.)
Here's what the handshake looks like with Hexchat doing SASL-only auth: …
=> implement #199

irc/accounts.go, irc/client.go, irc/idletimer.go, oragono.yaml
Two changes:
1. Bug fix: we didn't stop the `NickTimer` on client quit. This caused really weird stuff to happen if a client disconnected while the timer was running.
1. Allow re-registration of unverified accounts. I'm not sure if this is the right thing to do, but it handles cases where someone tries to sign up with the wrong email address, or the email doesn't get delivered correctly.
=> two nickname reservation fixes

irc/config.go, irc/server.go, oragono.yaml
The thing where importing `net/http/pprof` modifies the global `DefaultServeMux` is really gross. But it seems like the standard practice. Anyway, down the line, if we add native websocket support again, we'll have to be careful that we don't accidentally expose the pprof endpoints over the websocket listener.
=> add an option to expose a pprof http endpoint

.travis.yml
(Just want to see if this will work; I wasn't able to fully test it in my fork because, e.g., the code hardcodes `github.com/oragono/oragono/irc/passwd` as the package name.)
=> try to fix travis by pinning a goreleaser release

irc/client.go, irc/commands.go, irc/config.go, irc/fakelag.go, irc/fakelag_test.go, irc/getters.go, irc/handlers.go, irc/server.go, oragono.yaml
The model is that you can send some number of commands without being throttled (a "burst"); once you're throttled, we sleep the goroutine so that there's a minimum amount of time between each command; if you send no commands at all for some amount of time, both statuses will reset.
This doesn't take the specific command into account. I think anything involving a bcrypt operation (`ACC`, `AUTH`, and nickserv messages) is so expensive that anything else (like `LIST`) is small change.
=> implement fakelag (#189)

irc/client.go, irc/config.go, irc/errors.go, irc/getters.go, irc/server.go, irc/socket.go
Should be quite a bit simpler now; there's a chance that I introduced some kind of horrifying edge case too.
From what I understand, there's no need to drain channels when disposing of them, because channels and their contents are subject to normal garbage collection rules.
=> refactor irc.Socket

irc/fakelag.go, irc/fakelag_test.go
Commit message with the official explanation:
Basically, fakelag was counting the time imposed by its own sleeps as though
the user had themselves paused for that amount of time. Therefore, if a user
sent a large number of consecutive commands, every other command would pause
for the expected throttle interval, but the subsequent command would be
processed instantly (you'd get two back-to-back commands). This resulted in
throttled users being able to send at double the expected rate.
Unofficial explanation:
(a) I somehow miscounted the messages during manual testing (b) apparently in the unit test, I just wrote in whatever numbers would make it pass. (So the unit test is still valuable for ascertaining that future refactors preserve the correctness of the code. But as originally written, …
=> fix fakelag double-rate issue

irc/config.go, irc/database.go, irc/server.go, irc/utils/os.go, oragono.go, oragono.yaml
This is mostly straightforward, except for a couple points:
1. The concern from #224 rears its head again: the `Config` object is creeping into everything.
1. It's slightly counterintuitive that the automatic backup is only relevant when the upgrade appears to *succeed*, rather than when it fails (because on explicit failure, the whole upgrade can be rolled back as a single ACID transaction).
=> implement database auto-upgrades (#243)

irc/client.go, irc/socket.go
This is fiddly. The idea is:
1. Every time a write is triggered, start a new goroutine to do it
1. Use a channel as a trylock/semaphore --- I saw this in a [go-nuts discussion about whether Go needs a trylock](https://groups.google.com/forum/#!searchin/golang-nuts/trylock|sort:date/golang-nuts/vfbEGJCHGXM/9cHjdd0nYi0J) --- to exit if someone is already writing
1. Ensure that whoever was already writing eventually observes the need to write
The idea is that in the steady state, very few (or no) clients are actually in the middle of `conn.Write` calls, so this reduces the average number of goroutines per client from ~2 to ~1. Since each goroutine requires 8 kB of RAM for its stack, this can be a meaningful savings when dealing with large numbers of clients.
I ran ircstress in `connectflood` …
=> eliminate dedicated RunSocketWriter goroutine

irc/channel.go, irc/client.go, irc/semaphores.go, irc/server.go, irc/socket.go
The active ingredient here is the use of `ServerSemaphores` to permit at most 32 concurrent QUITs. The other changes are more cleanup than optimization (although they probably make things somewhat faster).
Anyway, lower-priority than #247, but I thought I'd put it up.
=> optimizations related to #237

irc/channel.go, irc/chanserv.go, irc/errors.go, irc/getters.go, irc/modes.go, irc/modes/modes.go, irc/modes/modes_test.go, irc/modes_test.go, oragono.yaml
I called it `AMODE` to emphasize the connection with accounts, as opposed to nicks. Maybe `AUMODE` would be better? Or something else entirely? The syntax looks like a `MODE` command, e.g., `/msg ChanServ AMODE #channel +h accountname`.
=> frontend for persistent account modes in channels

irc/chanserv.go, irc/modes.go, irc/nickserv.go, oragono.yaml
1. The oper privilege for account unregistration is now `accreg`, not `unregister`
1. Unregistering an account requires the account name and a confirmation code
1. Persistent channel admins cannot add/remove other admins
=> some tweaks to account/channel unregistration

irc/channel.go, irc/client.go, irc/config.go, irc/database.go, irc/getters.go, irc/handlers.go, irc/modes.go, irc/modes_test.go, irc/server.go, irc/utils/bitset.go, irc/whowas.go
The idea is that formerly, `applyConfig` copied a lot of state out of the `Config` struct and into the `Server` struct. For some time now, the `Server` struct has retained a pointer to the latest `Config`. So the implementation can be simplified by reading these values directly from the `Config` struct, and deleting the members of `Server` that were used to copy the data.
To the greatest extent possible, preprocessing of the config data has been moved into `LoadConfig`.
This is a bit risky because of all the edge cases so it's fine if you want to hold it until after the 0.12.0 release.
=> refactor rehash to rely more on server.config

irc/channelreg.go, irc/chanserv.go, irc/client.go, irc/config.go, irc/logger/logger.go, irc/nickserv.go, irc/server.go, irc/services.go
1. Fix #283 
1. In the logging config, allow the use of `type: "*"` and level `info` without triggering the warning about logging raw I/O
1. Add service command aliases, in particular, make `CS DROP` an alias for `CS UNREGISTER`
1. Fix a minor bug in `CS UNREGISTER` (the code would get confused if you tried to register and then unregister a channel in the same session, because the database time is lower-resolution than what you get from `time.Now()`)
=> assorted fixes

irc/channel.go, irc/modes.go
Stack trace: https://gist.github.com/slingamn/c6bd777e06326256a5c733d4a66dd609
This did not crash standard configurations of the server (because of #156); instead it would disconnect the client issuing the `SAMODE`.
=> fix a crash when SAMODE'ing in a channel you're not joined to

irc/modes/modes.go, irc/modes/modes_test.go
I figured out what happened:
1. In #269, I added nil receivers to the read-only methods of `ModeSet` to fix a crash
1. In #277, I accidentally removed the nil receiver from `ModeSet.HasMode`; this was not caught by unit testing because the underlying type of `ModeSet` also changed (from a map, which can be `nil`, to an array, which can't)
1. This caused the bug fixed by #269 to reappear, so it had to be fixed again in #291 (I thought it looked familiar!)
Anyway, this adds it back and improves the associated test so that it would have caught the regression in #277.
=> re-add nil receiver for ModeSet.HasMode

.travis.yml, irc/config.go, irc/database.go, irc/handlers.go, irc/server.go, oragono.yaml
I'm trying to set things up with full separation between oragono and its proxies (stunnel4 and webircgateway). In order to run them as separate users, oragono's unix domain socket must be mode `0777` (otherwise they can't connect).
I threw in a fix for #211.
=> configurable file mode for unix socket listeners

README.md
I noticed when testing this server out that `/NS REGISTER nick password` didn't work; I checked the code it and looks like all three of nick, email, and password are required: https://github.com/oragono/oragono/blob/c72a84e49fb136e471c1870d246a7d7e110d6ef9/irc/nickserv.go#L247
Thanks!
=> Correct NS REGISTER example

irc/client.go, irc/commands.go, irc/gateways.go, irc/handlers.go, irc/help.go
I'm trying to deploy dual stack to darwin.network. I ran into some compatibility issues with stunnel4. Specifically, stunnel4's method of doing dual stack is to listen on `::` (i.e., all IPv6 addresses); the Linux default is that this also listens on all IPv4 addresses, then uses the [v6 mapping scheme](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses) to represent v4 clients as having v6 addresses. This broke PROXY handling for two reasons, both of which are fixed here:
1. Handle PROXY lines with IPv6 addresses starting with :: (similar to WEBIRC in issue #211)
2. Strip v6 mapping from v4 addresses (i.e., turn `::ffff:192.0.2.128` back into `192.0.2.128`) when handling proxied IPs.
=> fix PROXY protocol support for IPv6

irc/accounts.go, irc/nickserv.go
The only weird thing is the syntax: you can do `NS PASSWD old new new` while logged-in and unprivileged, or you can do `NS PASSWD account newpassword` as an operator.
If you only have a certfp registered, you can't change your password this way (but an operator can). That seems fine for now.
=> implement NS PASSWD for password changes

oragono.go
docopt.Parse has been deprecated in
https://github.com/docopt/docopt.go/commit/943c2addfe613d2f08771caf67be9ead4e21029f
Not that anything would be broken before this change, but I was thiking it
might be useful contribution to the project. Feel free to close if you think
otherwise.
=> Replace docopt.Parse with docopt.ParseArgs

Makefile, gencapdefs.py, irc/accounts.go, irc/caps/defs.go, irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/commands.go, irc/config.go, irc/errors.go, irc/getters.go, irc/handlers.go, irc/history/history.go, irc/history/history_test.go, irc/modes/modes.go, irc/monitor.go, irc/nickname.go, irc/responsebuffer.go, irc/server.go, irc/socket.go, irc/types.go, irc/utils/bitset.go, irc/utils/bitset_test.go, irc/utils/crypto.go, irc/utils/crypto_test.go, irc/utils/text.go, irc/utils/text_test.go, oragono.yaml
This got big and messy. A few notes:
1. I got worried about history replay overrunning the client's sendq, particularly in cases where the client is joined to multiple busy channels. Instead, I added an interface to do blocking writes to the client's socket, bypassing the sendq. Based on my understanding of how progress works in Oragono, this shouldn't cause any problems, because we're writing to the client's socket from the client's own goroutine, and we're not holding any locks while we do it.
1. I think we might want to add a note to the spec that servers SHOULD verify resume tokens using a constant-time string comparison function, if one is available. (Python 3.6 has [secrets.compare_digest](https://docs.python.org/3/library/secrets.html#secrets.compare_digest), and Go has …
=> draft/resume-0.2 implementation, message history support

irc/channel.go, irc/client.go, irc/getters.go
I introduced #313 in fa83ccd82b4527. Before this commit, the code correctly read:
````go
channel.lists[InviteMask].Add(invitee.nickMaskCasefolded)
````
I changed `nickMaskCasefolded` to be the casefolded *nick*, not the nickmask. Anyway, here's what's in this branch:
1. Implement invites without modifying the invite exception list (instead, have the client store the set of channels they're invited to)
1. Joining a channel "uses up" your invite (so if you get kicked, you need another invite to return)
1. The `RPL_INVITING` response was buggy (and Hexchat displayed it incorrectly). The new parameters match both the [modern ircdocs entry](https://modern.ircdocs.horse/#rplinviting-341) and the behavior of Freenode.
=> fix #313 and a related issue

irc/accounts.go, irc/chanserv.go, irc/client_lookup_set.go, irc/hostserv.go, irc/nickname.go, irc/nickserv.go, irc/services.go, irc/utils/args.go, irc/utils/fieldsn.go
This is a low-priority refactor of the service framework. Two main changes:
1. Parameters now get parsed up front with `strings.Fields()` and passed to handlers as `[]string`, eliminating the use of `ExtractParam`.
1. `enabled` callbacks now take `*Config` instead of `*Server`
I also fixed a few cases where the behavior was incorrect or differed from the documentation.
The second commit is a fix for a dumb edge case in nickname reservation: if the server default was strict enforcement, and you were authed, then you couldn't change to a nickname that wasn't already reserved to your account (even if nobody owned it).
=> services refactor

irc/database.go, irc/dline.go, irc/handlers.go, irc/kline.go, irc/server.go, irc/utils/net.go, irc/utils/net_test.go
This was supposed to make things simpler. It probably made them more complicated. At any rate, it fixes some bugs: #144, plus an issue where `OperReason` wasn't being parsed correctly.
Some implementation notes:
1. Expiration of [dk]lines is now timer-based (rather than relying on query-time checks for expiration). The idea was that we could eventually use a radix tree for the queries, maybe something like kentik/patricia.
1. The address vs. network distinction for dlines is gone. Every ban gets normalized to a ban against an IPv6 CIDR --- v4 addresses/nets are mapped using the 4-in-6 prefix, then individual addresses are mapped to a /128 CIDR. The string keys that identify them strip this canonicalization for ease of use, e.g., `::ff:8.8.8.8/128` prints as `8.8.8.8` as expected.
=> refactor [dk]lines

irc/client.go
Reported by bogdomania on freenode. Formerly, we combined nick, username, and hostname into the nickmask, then tried to casefold the whole thing. In cases where hostname was LTR and either of the other strings was RTL, the casefold would fail due to the bidi rule.
With this branch, we casefold each component separately.
=> fix spurious bidi violations when casefolding the nickmask of an RTL nick

oragono.yaml
These are just used as examples, and prevent Oragono from starting
up if the host doesn't have an IPv6 stack (e.g. inside docker
containers).
See oragono/oragono-docker#5
=> Comment out 6668 bindings in default config

Gopkg.lock, Gopkg.toml, irc/accounts.go, irc/client.go, irc/client_lookup_set.go, irc/getters.go, irc/handlers.go, irc/idletimer.go, irc/nickserv.go, irc/strings.go, irc/strings_test.go
This is weird and fiddly and it may have bugs. Some notes:
1. Skeleton is always maintained side-by-side with the casefolded nick; both the skeleton and the casefolded nick must be computed from the original nick (you can't get one from the other).
1. Accordingly, additional nicknames reserved with `NS GROUP` must now be stored in their original, unfolded form (and folded again when they get loaded from the database).
=> implement confusables prevention (#178)

irc/handlers.go, irc/server.go, oragono.go, oragono.yaml
I was deploying #329, which had a schema change, and I had forgotten to enable database autoupgrades. So the deployment failed, which is expected. However, I ran into two problems:
1. I forgot to enable the `startup` log category, so the error message was suppressed
1. The program exited with code `0` despite the failure, which was confusing
The problem is that `startup` (and `shutdown`) are sort of vestigial at this point; almost all such messages are now associated with `Server.applyConfig`, which logs to the category `rehash`. Yet this is also incorrect terminology, since `applyConfig` runs during initial startup as well as rehash. Hence the decision to unify all these messages in the "server" category.
This change is not backwards-compatible, which we should mention in the changelog. …
=> rename the "startup", "rehash", and "shutdown" log types to "server"

irc/strings.go, irc/strings_test.go
`けらんぐ` was failing skeletonization, because one of the runes in its skeleton was disallowed by PRECIS:
````
:irc.darwin.network 400 * NICK :Could not set or change nickname: precis: disallowed rune encountered
````
All identifiers must independently pass PRECIS, so there's no real reason skeletonization should also use PRECIS. This switches the postprocessing of the skeleton to just do a pass of width normalization and then a pass of lowercasing (imitating the library calls used by PRECIS itself). (We are no longer iterating these operations four times --- but that seems like it's probably OK?)
=> more lenient casefolding for skeletons

irc/accounts.go, irc/client.go, irc/commands.go, irc/config.go, irc/connection_limits/limiter.go, irc/connection_limits/throttler.go, irc/connection_limits/throttler_test.go, irc/gateways.go, irc/getters.go, irc/handlers.go, irc/idletimer.go, irc/nickserv.go, irc/server.go, irc/utils/net.go, oragono.yaml
Implements the last-mentioned idea on #288.
This got into a lot of yak shaving because of the tangential connection to IPs. In short:
* All configurable lists of IPs/nets are normalized to a list of ipv6 CIDRs, using the utils from #329
* All IPs are normalized to v6, using the 4-to-6 mapping. (I explicitly stripped this mapping in #294, but it was a misdiagnosis; stunnel over ipv4 works fine with oragono without it.)
* To the maximum extent possible, we pretend unix domain sockets are actually 127.0.0.1
* "localhost" is an alias for both loopback CIDRs (127.0.0.0/8 and ::1/128), hence also for unix domain sockets
I tested this a bunch in my stage (genuine remote connections over both ipv4 and ipv6, direct and proxied through stunnel). I didn't test WEBIRC end-to-end with a real …
=> add sasl-only config option

irc/channel.go, irc/client.go, irc/commands.go, irc/config.go, irc/errors.go, irc/handlers.go, irc/help.go, irc/history/history.go, irc/history/history_test.go, irc/responsebuffer.go, irc/server.go, oragono.yaml
This has a zillion edge cases. Hopefully it's not risky, though. If you set `chathistory-maxmessages: 0`, `CHATHISTORY` will no longer be advertised in isupport (and will fail fast if invoked).
`HISTORY` is [grove.io's command](https://grove.io/blog/history-playback-irc.html) but with an explicit target argument.
This script was somewhat helpful for testing: https://gist.github.com/slingamn/da2f94eccead0edb38516b919d359c1d
=> add CHATHISTORY and HISTORY implementations

irc/handlers.go
Fixes if clients use the nick as username (which feels pretty common, I know I do it in some of my software), with our new restrictions those clients would no longer be able to connect!
=> Set uninteresting username if user's using a special nick

irc/client.go, irc/getters.go, irc/server.go
Together with a small amount of refactoring. In particular, `client.Register` had become sort of vestigial, so I removed it and absorbed it completely into `server.tryRegister`.
A couple safety checks were moved around: `tryRegister` doesn't need to check whether the client is already registered, and `tryResume` and `tryResumeChannels` don't need to check that `resumeDetails` is present. (All of these methods have only a single call site, so the check reads better if we just do it there.)
This passes the updated irctests in my ongoing branch: https://github.com/DanielOaks/irctest/pull/13
=> RESUME should end cap negotiation without requiring CAP LS

gencapdefs.py, irc/caps/defs.go, irc/client.go, irc/commands.go, irc/getters.go, irc/handlers.go, irc/resume.go, irc/server.go, irc/utils/crypto.go, irc/utils/crypto_test.go
cc @jesopo
This implements https://github.com/DanielOaks/ircv3-specifications/blob/0844bc2cb7e906ca9dceecab5033bafdbbca48ba/extensions/resume.md
It went quite well!
By design, a successful resume bypasses all auth checks (`PASS`, sasl-required, etc.). Formerly, client lookup by nickname was enough to ensure that the old client had successfully registered (and therefore passed all the auth checks). This implementation needs to check explicitly; this may or may not be worth noting in the spec.
=> update resume support to draft/resume-0.3

README.md, docs/MANUAL.md, irc/accounts.go, irc/handlers.go, irc/nickserv.go, oragono.yaml
1. Someone was having problems with ZNC's nickserv module (given that ZNC's SASL is broken) and I realized that it expects a different command format by default. Let's support this in the case where the client doesn't have a certfp (so they can't mean `/ns register $account`, meaning their certfp as the credential)
1. Most of the log categories mentioned in oragono.yaml don't actually exist! I added some loglines for the `accounts` category.
1. Updated the readme and the manual with some documentation changes that were missing from 
1. Make the land-grab check case insensitive
=> four small changes

gencapdefs.py, irc/caps/defs.go, irc/commands.go, irc/handlers.go, irc/help.go, irc/server.go
Quick and dirty implementation of [this proposed spec](https://github.com/ircv3/ircv3-specifications/pull/361). Nice and simple for us, shouldn't give any dramas from the looks of it.
=> Draft implementation of draft/setname

irc/accounts.go, irc/hostserv.go, irc/nickserv.go
1. Fix the weird `hs status` message reported by bogdomania on #382. (Since `hs status` can be used by a logged-out, opered-up user, it doesn't have the usual `authRequired` flag; we have to manually check this case.)
1. If SASL is required, account unregistration should disconnect all clients logged into the account. (In part this is just the right behavior. It also avoids weird edge cases where a client could unregister their account, which is the only way to log out of an account, then register a new one that would be unknown to the administrator, creating a back door. This is now blocked because in SASL-only mode, all remote clients are always logged in, and logged-in clients can't register accounts. I need to think more about how this case interacts with the exemption for "local" …
=> 2 small fixes

docs/MANUAL.md, irc/accounts.go, irc/errors.go, irc/handlers.go, irc/nickserv.go
This is a follow-up to #385. Basically, you can now set `accounts.registration.enabled = false` and still register accounts with `SAREGISTER`; this is in keeping with the documentation of the config key as "can users register new accounts?" (If the sudoer / config file owner wants to stop operators from using SAREGISTER, it suffices to take away the `accreg` capability from their oper blocks.)
This allows people to use the ircd from an exempted network, while forbidding them to register their own accounts. The manual is updated to describe this case.
=> allow SAREGISTER even when normal registration is fully disabled

irc/accounts.go, irc/channel.go, irc/channelreg.go, irc/chanserv.go, irc/config.go, irc/database.go, irc/getters.go, irc/handlers.go, irc/nickserv.go, oragono.yaml
* limit the total number of registrations per account (#280)
* when an account is unregistered, unregister all its channels (#221)
This is actually somewhat risky, and we can definitely hold it over for v0.14. But looking over the list of changes, this one seemed like it was...missing.
The default channels-per-account limit is 10, in homage to RFC 1459 (read somewhat out of context): "a limit of ten (10) channels is recommended as being ample for both experienced and novice users"
=> track channel registrations per account

irc/nickserv.go
Addresses #410 in a temporary way. Honestly, this has told me that I'm not at all happy with the current NS REGISTER command, so for v1.1.0 I reeeally want to overhaul it entirely and replace it with something more standard.
=> Band-aid NS REGISTER fix

oragono.yaml
I'm not sure this is suitable for merge as-is; I was thinking of it more as the start of a conversation.
This continues to support both plaintext and TLS by default, but nudges people gently towards disabling plaintext.
=> deprecate plaintext on 6667

install.sh
This makes it much easier to run on alpine which ships with
only a /bin/sh by default.
=> Use /bin/sh rather than /bin/bash

irc/client.go, irc/fakelag.go, irc/fakelag_test.go, irc/getters.go, irc/idletimer.go, irc/server.go
This is a somewhat pointless refactor (I'm not even sure it's worth the time required to review it). The goal was to put Fakelag and NickTimer directly inside the Client object (rather than storing pointers). While I was in the neighborhood, I made NickTimer more rehashable (it now behaves as one would expect if nick reservation is enabled or disabled by rehash).
=> remove indirections in Fakelag and NickTimer

irc/handlers.go
The `RENAME` C2S message takes as prefix the nickmask of the user who originated the rename, not the user receiving the message (as is the case for the fake part and join).
=> fix a regression introduced by #444

irc/accounts.go, irc/caps/set.go, irc/channel.go, irc/channelmanager.go, irc/channelreg.go, irc/chanserv.go, irc/client.go, irc/client_lookup_set.go, irc/errors.go, irc/getters.go, irc/handlers.go, irc/modes.go, irc/modes/modes.go, irc/semaphores.go, irc/server.go, irc/stats.go, irc/utils/bitset.go, irc/utils/bitset_test.go, irc/utils/sync.go, irc/whowas.go, irc/whowas_test.go
This refactors a bunch of channel registration stuff, mostly to prepare for #357 when we expect the datastore to be remote and significantly higher in latency:
1. Operations should not block on the datastore unless they need to (so we shouldn't have to look in the datastore every time someone joins a new channel)
1. The datastore should not be accessed while holding any global locks
1. There shouldn't be a thundering-herd effect on channel joins (the server is restarted, everyone tries to rejoin the same channel, each join sees that the channel data isn't loaded yet and tries to load it)
1. Writes of channel data now use a system modeled after `irc/socket.go` as of #236; we maintain dirty bits for the channel, then each time the channel becomes dirty, we acquire a trylock and spin off a …
=> refactor channel registration

irc/modes.go
I triggered this deadlock (introduced in #446) in production just now:
````
goroutine 135568 [semacquire, 4 minutes]:
sync.runtime_SemacquireMutex(0xc000083cf4, 0x857b00)
/usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc000083cf0)
/usr/local/go/src/sync/mutex.go:134 +0x109
sync.(*RWMutex).Lock(0xc000083cf0)
/usr/local/go/src/sync/rwmutex.go:93 +0x2d
github.com/oragono/oragono/irc.(*Channel).MarkDirty(0xc000083ba0, 0x8)
/home/oragono/go/src/github.com/oragono/oragono/irc/channel.go:183 +0x3d
github.com/oragono/oragono/irc.(*Channel).ProcessAccountToUmodeChange(0xc000083ba0, 0xc000043880, 0x2b00000068, 0xc0001b43b8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/oragono/go/src/github.com/oragono/oragono/irc/modes.go:293 +0x567
github.com/oragono/oragono/irc.csAmodeHandler(0xc0001938c0, …
```
=> fix a deadlock in CS AMODE

gencapdefs.py, irc/accounts.go, irc/caps/defs.go, irc/caps/set.go, irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/commands.go, irc/config.go, irc/gateways.go, irc/getters.go, irc/handlers.go, irc/idletimer.go, irc/nickname.go, irc/nickserv.go, irc/responsebuffer.go, irc/roleplay.go, irc/server.go, oragono.yaml
This is an unusually dangerous change. Here are the active ingredients:
1. `Client` now has a field `sessions` of type `[]*Session`
1. A `Session` holds a `Socket` and other data that is local to an individual TCP connection, in particular the cap set
1. `Client.sessions` is effectively a refcount system for the client; if its length drops to `0`, the client is destroyed
1. `ResponseBuffer` now targets a single `*Session`. Any state changes in the response have to be manually forwarded to other connected sessions (i.e., `ResponseBuffer` doesn't attempt to automatically cc them).
1. If allowed by default in the server config, or the client negotiates the cap `oragono.io/bnc` (to be drafted), `ClientLookupSet.SetNick` will allow the client to reattach to an existing session
1. If …
=> minimum viable product for bouncer

irc/client_lookup_set.go, irc/handlers.go, irc/server.go
It looks like cap-notify's been a little busted. Not related to the bnc stuff, just in general probably. This PR fixes that up a little.
It seems there's still s'more to do with regards to getting the values to be passed-thru on cap value replies, seems to be sending out empty lines currently. The SASL enable/disable block should reeeally just use the same structure as the STS section below, that handles things a whole lot more nicely.
Issues this should resolve:
- Currently, if someone sends `CAP LS 302` they won't automagically receive `cap-notify` messages (as the spec indicates they should). This PR should mean they will, without having to explicitly request that capability separately.
- Currently, if someone sends `CAP LS 303`, they won't get any of the `302` stuff (specifically, the …
=> Fix cap-notify

irc/channel.go, irc/getters.go, irc/modes.go, irc/modes/modes.go, irc/modes/modes_test.go, irc/modes_test.go
1. #400 
1. STATUSMSG didn't add the designated prefix to the channel (I have an irctest covering this in an unpushed WIP branch)
1. `NAMES` didn't respect invisibility (this diff is easier to read with `-w`, i.e., ignoring whitespace changes)
=> three fixes

irc/channel.go, irc/handlers.go
This fixes a regression from #467 (non-members could no longer `WHO` a channel, even a non-secret one), and also makes consistent that operators can see through the secret channel mode and invisible user mode.
=> tweaks to NAMES / WHO privacy

gencapdefs.py, irc/accounts.go, irc/caps/defs.go, irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/commands.go, irc/gateways.go, irc/getters.go, irc/handlers.go, irc/history/history.go, irc/history/history_test.go, irc/nickname.go, irc/nickserv.go, irc/responsebuffer.go, irc/server.go, irc/utils/text.go
This checks the first five boxes on #457. It's a bit fiddly, lots of edge cases and inadequately tested code paths.
=> improvements to message replay code

irc/accounts.go, irc/channel.go, irc/client.go, irc/config.go, irc/getters.go, irc/handlers.go, irc/isupport/list.go, irc/modes/modes.go, irc/semaphores.go, irc/server.go, irc/snomanager.go, oragono.yaml
1. ZNC 1.6.x is going to be common in the wild for at least another 4 years (when Ubuntu 18.04 goes EOL). Broken SASL has the potential to hold people back from adopting new practices (SASL over TLS everywhere together with strict nickname reservation). I think we should bite the bullet and add compatibility code for this. I tested this change with 18.04's package of ZNC 1.6.6+deb1ubuntu0.1.
1. I put in a switch to turn off the "force trailing" hack as well, since I was in the neighborhood.
1. This is something I've been contemplating for a while: I changed `server.Config()` to be an atomic pointer load. This is kind of silly because the saving is fairly small (on my system: from 15 nanoseconds for an uncontended rlock acquisition, to less than a nanosecond). On the other hand, it's …
=> add client compatibility switches

irc/channel.go, irc/utils/crypto.go, irc/utils/crypto_test.go
Now that we're emitting unprefixed, final-standard values of `msgid`, I wanted to have a more precise handle on what kinds of msgid we emit. In particular, this change guarantees that our msgids are always 26 characters from our customized b32 alphabet. This should be helpful if we ever design/adopt a new scheme.
=> formalize token munging code

irc/utils/semaphores.go, irc/utils/semaphores_test.go
Not used currently, but eventually I want this for locking user account data (i.e., the race condition described on #499).
=> add AcquireWithTimeout for semaphores

irc/idletimer.go, irc/nickserv.go, oragono.yaml
This is more of a discussion ticket with an attached patch :-)
Timeout-based enforcement on darwin.network has been disruptive and unpopular: people log in, everything seems fine (they may have been missing the notice due to the lack of a fully-specified nickmask, which this PR also corrects), then they get renamed to `Guest-1c9d95f548e09a82` or something equally impenetrable.
In contrast, clients handle strict enforcement better: they respond to `433 ERR_NICKNAMEINUSE` by adding a `_` to the nickname and moving on. (Once registration completes, you can identify to nickserv and switch manually; now that we have #261 in place, there's no one in practice who needs to automate this.) So there's an interesting question about how to retrain people not to automatically believe that `shivaram_` …
=> make strict enforcement the default

irc/strings.go, irc/strings_test.go
Explanation in the commit message.
Since this is a potential security issue, it's a candidate for merging now, before the final release.
=> fix an edge case in skeletonization

Gopkg.lock, Gopkg.toml, irc/strings.go, irc/strings_test.go
Sorry to be second-guessing this AGAIN but the m -> rn thing has been bothering me; it seems like the most likely to interfere with legitimate use (although it's still extremely unlikely).
"Purely alphabetic lowercase ASCII identifiers do not collide with each other" seems right to me.
=> remove m -> rn mapping

irc/chanserv.go, irc/handlers.go, irc/help.go, irc/hostserv.go, irc/nickserv.go, irc/services.go
#587 except not broken.
1. DRY "banner" descriptions of each services
2. `/HELP NICKSERV` now refers the user to `/NICKSERV HELP`, etc.
3. Fix double translation of `textGenerator` output
=> refactor /HELP for services

irc/config.go
tor-listeners.listeners was checked against listen,
but listen is obsolete now, so config load would fail
on a config that used the new style `listeners` instead of
`listen` --- unless tor-listeners.listeners was empty, which
it should be under the new style, but there's no need to enforce
that
=> remove obsolete consistency check

irc/channel.go, irc/client.go, irc/config.go, irc/history/history.go, irc/history/history_test.go, irc/server.go, oragono.yaml
My main concern is that the interface for server admins (`autoresize-window` and its description) is too confusing.
=> autoresizing of history buffers (#349)

irc/getters.go
Produces a small savings on the chanflood benchmark.
=> optimize Sessions() at the expense of AddSession()

irc/utils/semaphores.go
1. Make the semaphore hold empty structs instead of bools
1. Make acquire a send and release a receive instead of the other way around; this is mentioned in the [memory model documentation](https://golang.org/ref/mem) and avoids having to fill the semaphore with items up front
=> make semaphores O(1) in storage

gencapdefs.py, irc/caps/defs.go, irc/caps/set.go, irc/caps/set_test.go, irc/handlers.go, irc/server.go, irc/utils/text.go, irc/utils/text_test.go
1. Refactor line generation into a helper class (I might end up using this for `Channel.Names` as well)
1. Raise the line length limit for `CAP LS 302` as high as possible; in particular, the output from the default config will fit on a single line as long as the server name is 35 characters or less
=> tweaks to cap listing

README.md, distrib/docker/Dockerfile, distrib/docker/README.md, distrib/docker/docker-compose.yml, distrib/docker/run.sh, docs/MANUAL.md
Move all the docker files to distrib/docker, and update instructions to match.
I've (presumptuously) removed the BETA label for docker and added a brief section in the main manual as well.
When this is merged we'll need to update the Docker Hub config, which I guess is a job for @DanielOaks? (If you'd rather I'd do it, I'm happy to but will need permissions on Docker Hub)
=> Merge docker files from oragono-docker repository

irc/client.go, irc/config.go, irc/gateways.go, irc/getters.go, irc/nickserv.go, irc/server.go, irc/utils/net.go, irc/utils/net_test.go, oragono.yaml
This is actually a bit fiddly because of the part where I moved the hostname lookup. An intermediate version of this change was buggy and broke RESUME (the new hostname wasn't getting resolved at all during resume, then I was trying to copy it over the old hostname, with disastrous consequences). This was caught by the integration test suite.
=> #688: forward-confirmed reverse dns

irc/handlers.go
As in RFC4616: `message   = [authzid] UTF8NUL authcid UTF8NUL passwd`
authzid is 0th (called accountKey in code), authcid is 1st param
=> Fix `authcid` variable name

gencapdefs.py, irc/caps/constants.go, irc/caps/defs.go, irc/channel.go, irc/client.go, irc/client_test.go, irc/commands.go, irc/config.go, irc/handlers.go, irc/help.go, irc/responsebuffer.go, irc/server.go, irc/utils/text.go, oragono.yaml
This implements https://github.com/ircv3/ircv3-specifications/pull/398 with fallback msgids (currently tagged `draft/fmsgid`). As usual, the diff is more readable when ignoring whitespace changes :-)
Due to security concerns, multiline is disabled unless explicitly configured in the `limits` section, although it is enabled in the new default config.
Some of the changes here ("collapsing" the outer labeled-response batch, config "diff", and the new shorter batch IDs) are useful even without multiline.
=> implement draft/multiline

irc/accounts.go
This reverts commit a120cc24436a69402f95644eb5e1ef92c04148b2.
I realized the point of this is to "park" the certfp so that it can't be registered by anyone else during the verification period. This seems acceptable. You can't log in before verification because `AuthenticateByCertFP` checks the verified flag on the account.
=> Revert "never set the certfp lookup key before verification"

irc/client.go
In the k8s PROXY-before-TLS setting, we don't know all the IPs
of the load balancers, so we can't whitelist them, so they're at
risk of being d-lined.
=> don't check the real IP for bans on proxy-before-TLS

irc/config.go, irc/server.go
This is a minor bug in #695. When a non-PRECIS casemapping was enabled, initially `UTF8MAPPING=rfc8265` would be sent in isupport, and then the first rehash would remove it with `005 -UTF8MAPPING`, when in fact it should never have been sent at all. This bug was caused by reading the global, instead of reading the appropriate member of the `Config` object itself.
To avoid getting confused again, I'm moving `Config.generateISupport` into `irc/config.go` where it belongs.
=> fix incorrect values of UTF8MAPPING for non-PRECIS casefoldings

gencapdefs.py, irc/caps/constants.go, irc/caps/defs.go, irc/channel.go, irc/client.go, irc/config.go, irc/handlers.go, irc/history/history.go, irc/nickname.go, irc/responsebuffer.go, irc/server.go, irc/utils/text.go, irc/utils/text_test.go, oragono.yaml
This removes maxline support, and also makes our multiline implementation conform to the current version of https://github.com/ircv3/ircv3-specifications/pull/398 (no fallback msgids, fallback PRIVMSG other than the first are sent without a msgid).
I feel conflicted about this because I think it makes `CHATHISTORY` harder for client developers to use (unless they add full support for multiline, they won't be able to deduplicate all history messages by msgid). But I'm not sure there's much appetite for a solution that avoids this.
=> remove oragono.io/maxline-2 and fmsgid

oragono.yaml
From discussion on the multiline spec PR, our sendq value is very conservative compared to Unreal and Inspircd (even considering that the client's own responses don't use the sendq).
The maximum size on the wire of a multiline is roughly max(max_bytes, 100 * max_lines), so the sendq holds about 10 maximal multilines, which seems OK I guess.
=> increase default sendq and multiline max-lines

irc/client.go, irc/server.go
The active ingredient is moving the hostname lookup before `performNickChange` (which is what actually attaches the session to the old client).
=> mitigate #772

go.mod, irc/accounts.go, irc/config.go, irc/errors.go, irc/ldap/LICENSE, irc/ldap/config.go, irc/ldap/grafana.go, irc/ldap/helpers.go, irc/ldap/login.go, irc/nickserv.go, oragono.yaml
Successor to #779.
This does some very aggressive copying and pasting of Grafana's code and configs --- correctly handling all the different cases for group membership is really finicky and I think the best thing for us to do is just steal their interface (i.e., config format) and implementation entirely. As I understand it, MIT and Apache 2.0 are compatible, so this is unproblematic.
@mattouille I'd be interested in code review and maybe some additional testing for this if you have time --- you should also feel free to make code changes.
=> LDAP support

oragono.yaml
These are changes I recommended for hashbang.sh's pilot deployment. It occurred to me that I'd recommend them in any context. so I wanted to make them the recommended defaults.
1. bcrypt is very slow (by design) and poses a thundering-herd problem after server restarts. This makes it 8x faster (I think on the order of 10 milliseconds on modern Intel hardware?).
2. Allowing bouncer by default is working OK on darwin.
3. Strict enforcement seems like a sane default (and it's working OK on darwin).
=> change some recommended defaults in the config

oragono.yaml
@DanielOaks I won't merge this without your approval.
I feel like public plaintext is a bad default for 2020, and goes against the ideas in https://github.com/ircv3/ircv3-ideas/issues/45. But if you think this is an unfriendly default, or insufficiently batteries-included, I get it.
@csmith I'm not 100% clear on how this would interact with the Docker configs; would 6667 still be exposed despite this change, because of `EXPOSE` and `-p`?
=> new default: no public plaintext listener

oragono.yaml
From testing on darwin; shaves 3 characters off the cloaked hostname,
and 64 bits of entropy is fine (a collision is expected after 2**32
~= 4 billion distinct CIDRs).
=> reduce recommended cloak bits from 80 to 64

irc/accounts.go, irc/errors.go, irc/nickserv.go, irc/server.go
How confident am I that I caught all the possible cases? Not very. But here's what this does:
1. You cannot modify `always-on` with `NS SET` unless your nick exactly matches the account name (either you are the always-on client, or you have the right nick so it's OK for you to become always-on). There is an exception for `NS SASET`.
2. As the server operator, you cannot modify the default value of `always-on` during a rehash (since this might change the always-on status of existing clients unpredictably)
3. Registered clients cannot authenticate to the account of an always-on client. (If you are unregistered, you can authenticate, which will then become a reattach.)
=> fix #821, maybe

CHANGELOG.md
Issue #745 affected channels, not accounts. Since confusable protection
for channels was not implemented at all in 1.2.0, this bug was never present
in a release and shouldn't be in the changelog.
=> remove erroneous changelog entry

irc/client_lookup_set.go
`Guest-34` would get corrected to `Guest-Guest-34`, this fixes that.
=> fix double-application of guest prefix

irc/accounts.go, irc/channelmanager.go, irc/channelreg.go, irc/errors.go, irc/handlers.go, irc/nickserv.go
This was easier than I expected. Basically, the "unregister" and the "erase" operations share almost all their code. "Unregister" sets a database key "parking" the account name indefinitely. "Erase" deletes the key if present.
=> make account names permanent identifiers

.travis.yml, Makefile, oragono.go
`NewServer` parses the config and actually starts the server. Then `--smoke` suppresses the wait-for-quit-signal loop, so it immediately exits. This correctly detects the current problem with the Finnish translations.
=> add smoke test

irc/accounts.go
1. Fix #908 
2. With strict nickname reservation, the nickname should be reserved even after unregistration
=> more updates to permanent account identifiers

irc/channel.go, irc/chanserv.go, irc/handlers.go, irc/modes.go, irc/modes/modes.go, irc/modes/modes_test.go
This propagates CS AMODE changes to the actual modes, but not the other
way around.
Also fixes #909.
=> partial implementation of #729

docs/MANUAL.md
Commit f920d3b ("fix #530, #721") removed the ACC command, update the manual to reflect this.
This caused me a bit of confusion until I noticed that the command was previously removed before 2.0.0.
=> Devel.fix documentation to match acc removal

README.md
My sense is that this link is no longer very beneficial to either oragono or darwin.
=> remove darwin.network from the readme

irc/server.go
Reported by jess on #oragono
sorry for the later 2-line diff (just the editor trimming whitespace)
=> use servername instead of nickmask for RPL_UMODEIS prefix

irc/accounts.go, irc/chanserv.go, irc/nickserv.go
These commands search the registered nicknames/channels for ones matching the provided regex, or return the entire list.
Only operators with chanreg (for ChanServ) or accreg (for NickServ) capabilities can use LIST.
Fixes #974
=> Add ChanServ and NickServ LIST commands.

irc/client.go
This change is not very important.
=> use shorter batch IDs

conventional.yaml, irc/server.go, oragono.yaml
This is a pain point for websockets. Hard to see how it could cause any problems.
=> new recommended default: proxy allowed from localhost

irc/client.go, irc/handlers.go
Opers can still see +i users.
Fixes #990.
=> Hide +i users from WHO * queries.

irc/client.go, irc/config.go, irc/modes.go, irc/modes_test.go
This ensures that counts like the number of invisible users are updated
correctly.
=> Call ApplyUserModeChanges for default user modes.

irc/channel.go
This affects /TOPIC, /INVITE, and a few others.
=> treat channel founder as such even if they don't have +q

go.mod, go.sum, irc/client.go, vendor/github.com/oragono/go-ident/client.go, vendor/modules.txt
This worked correctly on the testnet (BitBot's nickmask is now `BitBot!bitbot@muv8gzn63bjkn.oragono` as expected).
=> upgrade go-ident to fix parsing issue

conventional.yaml, irc/accounts.go, irc/channel.go, irc/chanserv.go, irc/client.go, irc/config.go, irc/handlers.go, irc/history/history.go, irc/histserv.go, irc/mysql/config.go, irc/mysql/history.go, irc/nickname.go, irc/roleplay.go, irc/server.go, irc/services.go, oragono.yaml
This change is kind of lame. Probably no one will ever use #858. But it's important to be able to claim the ability to do it.
=> fix #858 and #383

irc/mysql/history.go
Reverts oragono/oragono#1013
This has a backwards compatibility problem so I'm reverting it for now.
=> Revert "Add support for Unix domain sockets"

irc/server.go, irc/signals.go, irc/signals_plan9.go
@clukawski got oragono running on 9front (a Plan 9 fork). This was the only compilation issue.
=> fix plan9 support

irc/handlers.go
Closes #968. We were already compliant, but we weren't labeling the response correctly.
=> include account-notify in the response batch

irc/accounts.go
don't need to send account-notify * (logout notification)
because either we never sent the initial account-notify
(if we are being logged out as part of fixupNickEqualsAccount)
or else we are immediately going to kill the client
(if we are being logged out as part of unregister/erase)
=> clean up account-notify logout notification

irc/nickserv.go
14:39 <oragono_> **erase** oragono
14:39 -NickServ(NickServ@localhost)- Warning: erasing this account will allow it to be re-registered; consider UNREGISTER instead.
14:39 -NickServ(NickServ@localhost)- To confirm, run this command: /NS **UNREGISTER** oragono 8srfw
=> /ns erase should confirm with /ns erase rather than unregister.

irc/channel.go, irc/client.go, irc/responsebuffer.go, irc/utils/text.go
1. TAGMSG were incorrectly being considered multilines, because Is512() was checking the wrong thing, and then not getting replayed at all (unclear whether this is a bug in 2.0.0 or a regression from development, so not sure whether it gets a changelog entry)
2. Playback of TAGMSG should depend on event-playback, not on message-tags (this is a bug in 2.0.0 and should get a changelog entry)
I wrote an irctest for this but GitHub won't let me PR it right now, whatever.
=> fix TAGMSG playback

.gitignore, conventional.yaml, oragono.yaml
I'm not 100% sure about this, but anecdotally the current names are a source of confusion (sometimes people transpose the filenames). These names match the names used by Let's Encrypt, making it easier to upgrade.
Thoughts?
=> change the default self-signed certificate filenames

irc/handlers.go
This avoids "No such nick" responses to +draft/typing TAGMSG, etc.
=> Ignore non-privmsg commands to services.

irc/client.go, irc/config.go, irc/modes.go, irc/modes_test.go, irc/server.go, irc/stats.go
Previously, we were applying defaults before the user had completed registration. This meant that the number of invisible users was incremented when the user connected, and then the total was incremented when registration was completed.
Now both counters are updated at the same time. If a user disconnects prior to registration, +i has not yet been applied so it would not be decremented.
Fixes #1077.
=> Apply default user modes just before registration.

irc/isupport/list.go
=> don't add trailing = to ISUPPORT tokens when value is empty string

irc/config.go, irc/server.go
This matches Insp's new behaviour and allows an initial better way for clients to see which other users are bots. See also https://github.com/inspircd/inspircd/commit/31815edd6a6b98434bace5359234d2b47397ee0a
=> Copy Insp's new BOT ISUPPORT token and WHO behaviour

irc/channel.go, irc/utils/glob.go, irc/utils/text.go
`strings.Builder` is faster in the cases where the result is used as a string (with `bytes.Buffer`, the mutable buffer has to be copied to produce an immutable string).
=> use strings.Builder instead of bytes.Buffer where applicable

irc/handlers.go, irc/help.go, irc/modes.go, irc/modes/modes.go
Adds no-CTCP usermode as per #1007
=> Add +T no-CTCP usermode

irc/config.go, irc/handlers.go, irc/numerics.go, irc/server.go
first attempt. i assume there's going to be a few issues of artistic preference and me not being a Go expert so please be brutal.
mostly used InspIRCd's WHOX implementation as a reference for this (thnx @Sadiecat ❤️) but also charybdis and http://faerion.sourceforge.net/doc/irc/whox.var
much like charybdis, we do not actually support the `filter` part of WHOX. I really do not think it's important enough for the complexity it would add to this PR.
I've not yet implemented the `o` field (channel power level) because I couldn't quite figure out how I'd want to give channel status modes int values. thought I'd leave that up to a discussion,
=> implement WHOX

conventional.yaml, default.yaml, irc/channel.go, irc/config.go, irc/handlers.go, irc/history/history.go, irc/server.go
Fixes #1172.
`Config.History` is no longer a value type, so it can no longer be compared with `==`, necessitating the new comparison method.
=> make TAGMSG storage configurable

irc/accounts.go, irc/client.go, irc/client_lookup_set.go, irc/getters.go, irc/handlers.go
Implements #1065. Added implementation notes to the issue.
=> Persist realname for always-on clients

irc/accounts.go, irc/client.go, irc/getters.go
@bogdomania reported that there are code paths that do not create always-on clients as expected. This should be a lot cleaner.
=> clean up always-on state machine

irc/getters.go
If force-nick-equals-account is disabled, then this could cause
a client with a non-reserved (or grouped) nick to become always-on.
(This can't happen with `/NS SET always-on true` because we check in
advance.)
=> fix an edge case with `/NS SASET user always-on true`

irc/channelmanager.go, irc/getters.go, irc/handlers.go, irc/numerics.go
Fixes https://github.com/oragono/oragono/issues/1122
New draft: <https://github.com/ircv3/ircv3-specifications/pull/420>
Former draft: <https://github.com/ircv3/ircv3-specifications/pull/308>
Quoting the new draft commit message:
> Changes from the earlier PR so far:
> 
>    1. Drop MODE message from fallback requirements
>    2. Switch to standard replies FAIL codes for new error cases
>    3. Existing error numerics such as ERR_CHANOPRIVSNEEDED are preferred
>    4. Move normative fallback mechanism to its own section and add an example
>    5. Mention case changes explicitly
>    6. Don't use RFC keywords in non-normative security section
1. already done
2. done in commit https://github.com/oragono/oragono/commit/9d86a76f655b05313583f9db7a569c1a69ebe3d5
3. already done
4. already done …
=> Update draft/rename impl

irc/help.go
@DanielOaks when this kind of thing happens, existing translations don't go away entirely, right? They're still on the site as a reference for creating a new translation?
=> correct trailing space on +R usermode documentation

irc/utils/proxy.go
cc @RyanSquared @daurnimator (just as an FYI; I'll send a PR for gitops later)
`http.Server` was considering these fatal errors and exiting, closing the listener:
https://github.com/golang/go/blob/9706f510a5e2754595d716bd64be8375997311fb/src/net/http/server.go#L2944-L2957
This is still a bit awkward because even with `Temporary()` returning true, the server loop will back off and sleep for up to a second. Avoiding this seems nontrivial. Since these proxy-before-TLS listeners can only be exposed to trusted clients anyway, this doesn't seem to pose a DoS issue. (I assume the bad proxy lines were coming from the healthcheck, which just opens and closes the port?)
I tested this on my stage.
=> fix websocket listeners with proxy-before-TLS closing on bad PROXY lines

.gitmodules, .travis.yml, Makefile
This adds irctest as a submodule. I don't know if this is a good idea at all. But the idea (compare #1270) is that you can push a branch to the irctest repo, then update the submodule pointer in your oragono branch, and then rely on the normal conflict resolution mechanism for submodules.
=> run irctest in travis

Dockerfile
This is no longer necessary, since vendor/ is now part of the main tree.
=> attempt to fix #1282

irc/channel.go, irc/client.go, irc/handlers.go, irc/help.go, irc/modes/modes.go
This fixes #484. It's a squash of #1298.
=> auditorium mode

conventional.yaml, default.yaml, irc/client.go, irc/config.go, irc/handlers.go, irc/server.go
WHO and WHOIS are the only commands I could find that expose the operator status.
This also disables snomasks by default, as discussed on #1309.
=> hidden operators, tweaks to default operator config

irc/client.go
This affects RPL_WHOISACTUALLY and possibly others.
Follow-up to #1313
=> separate rawHostname and cloakedHostname for always-on clients

conventional.yaml, default.yaml, irc/client.go, irc/config.go
suppress-ident was never in a release. However, this needs to be changelogged as a minor compatibility break, since it may invalidate stored bans of always-on clients. (We should also alert hashbang since they're using an unreleased build with suppress-ident enabled.)
=> replace suppress-ident with coerce-ident; make coerce-ident a recommended default

irc/channel.go, irc/chanserv.go
reported by @mogad0n :
1. The sources of AMODE changes were inconsistent (sometimes the server, sometimes chanserv); now it's always the server
2. SAJOIN did not send a MODE line to the originating client
=> fix output bugs in AMODE handling

distrib/atheme/atheme2json.py
For example, if the mlock is set to `-i`, `i` is not present in the `modes` set a few lines above and thus it would error.
```python
modes = {'n', 't'}
```
I'm inclined to think that the negative mlock feature doesn't behave correctly. Or atleast, Oragono's interpretation of the Atheme feature is not the same as how Atheme would treat it as far as I can understand it. The mlock of `-i` (or `-n`) would prevent anyone from ever setting those modes on the channel. Which this does not appear to be the case on Oragono. I think this is just setting the channel modes to be equivilent to the MLOCK which isn't what the MLOCK is used for in Atheme. However, this fix is orthogonal to that issue, as I believe that applies also to the `n` and `t` modes.
Atheme help on this feature:
```
<ChanServ> …
```
=> Allow atheme2json to handle mlock mode removal (outside of `-t` or `-n`)

distrib/atheme/atheme2json.py
This makes invoking the script multiple times with the same input return the same result, which may not be the case before because sets are unordered and thus the channel modes can become reordered across multiple invocations of the script.
This is something I noticed while testing, is that the order flipped making my tests fail sometimes.
```
$ python atheme2json.py services.db test1.json
$ python atheme2json.py services.db test2.json
$ openssl sha1 *.json 
SHA1(test1.json)= ca80825857bd56dc6f170168e70aacefaf762300
SHA1(test2.json)= 0a0ad289d664b14f929797d4e7cb85810c3a8391
```
```
$ python atheme2json.py services.db test1.json
$ python atheme2json.py services.db test2.json
$ python atheme2json.py services.db test3.json
$ python atheme2json.py services.db test4.json
$ python …
```
=> Make atheme2json sort channel modes

irc/history/history.go, irc/history/history_test.go, irc/ircconn.go, irc/ircconn_test.go, irc/socket.go, irc/utils/math.go, irc/utils/math_test.go
Not necessarily for merge; I'm not entirely sure this code is correct.
This produces about a 20% savings in RSS on the connectflood benchmark (i.e., connecting a lot of concurrent clients that don't do anything on the server).
=> more memory-efficient implementation of line reading

distrib/atheme/atheme2json.py
- flatten channels owned by GroupServ groups to the first group founder, as mentioned in https://github.com/oragono/oragono/issues/465#issuecomment-734937334
- translate channel flag +a to the corresponding amode
=> atheme2json enhancements

default.yaml, traditional.yaml
Whenever CIDR is mentioned in the config, it's in combination with IP so
talking about addressese in these points gives wrong impression that a
domain name would be valid as those are often thought as addresses.
=> {default,traditional}.yaml: refer to IPs/CIDR instead of addrs

irc/handlers.go
This is fairly unimportant. I just grepped for magic numbers related to line length (`\<51[0-9]\>`) and saw this one.
=> make CAP LS/LIST respect the MaxLineLen constant

irc/channelmanager.go, irc/handlers.go
Channel rename (both of registered and unregistered channels) would leave
the old name unreclaimable.
=> fix critical bugs in RENAME

irc/client.go, irc/config.go, irc/ircconn.go, irc/listeners.go
This adds a cap named `draft/utf8-only`; my sense is still that this proposal belongs in the public draft process, as part of the conversation around the status of legacy encodings. If you have strong feelings, I can go back to a vendor prefix.
This also enforces that (websockets implies enforce-utf8), and cleans up some enforcement code.
=> initial work on #1483

irc/client.go, irc/getters.go
checkAlwaysOnExpirationNoMutex was respecting registered status, but
always-on clients were not considered registered at the time of the
initial check, so they were being created regardless of expiration.
=> fix always-on expiration checks

default.yaml, traditional.yaml
Two objectives:
1. Reduce thundering-herd effects on server restart (a cost of 4 should be
approximately 1 millisecond of CPU time per reconnecting client)
2. Speed up mobile reattach as much as possible (see also #1420)
=> reduce recommended bcrypt cost to the lowest allowed value

go.mod, go.sum, vendor/github.com/goshuirc/irc-go/ircmsg/message.go, vendor/modules.txt
As discussed on goshuirc/irc-go#36, there are no security implications for Oragono. Given the new message caching layer, I expect negligible performance implications as well.
=> bump irc-go to latest

irc/handlers.go
1. Send COMPLETE_CONNECTION_REQUIRED instead of DISALLOWED
2. Include the account name in all FAIL messages
=> improve compatibility with published register spec

irc/client.go, irc/ircconn.go, irc/listeners.go
1. Text and binary frames are accepted
2. Text frames are sent by default
3. Binary frames are sent to clients who negotiate `binary.ircv3.net`
4. Non-UTF8 data is not accepted (enabling websockets still enables UTFONLY)
=> implement candidate compromise proposal for websockets

docs/MANUAL.md
The +M channel mode is documented twice. Merge the two sections.
Clarify that +R restricts both joining and speaking, but does not kick existing unregistered users.
=> Minor documentation updates.

default.yaml, go.mod, go.sum, irc/channel.go, irc/client.go, irc/config.go, irc/handlers.go, irc/message_cache.go, traditional.yaml, vendor/github.com/goshuirc/irc-go/ircmsg/message.go, vendor/github.com/goshuirc/irc-go/ircreader/ircreader.go, vendor/modules.txt
Implements #1577, but the issue should remain open until we clean up the debugging loglines.
This splits the baby: `default.yaml` has `allow-truncation: false` (and I plan for the test suite to run in this mode), but `traditional.yaml` has it as `true`, and it will default to true when unset (so no one gets surprised by their bots breaking).
=> deprecate message truncation

default.yaml, irc/handlers.go, traditional.yaml
closes #1153
design choices:
- pretend `$` magic doesn't exist if you're not an oper with `massmessage` capab
- don't do message tags
- `Erroneous target` when glob compilation fails
=> implement mass/global messaging

irc/handlers.go
Reported by @ajaspers
```
REGISTER * shivarampassphrase
:oragono.test 400 * :Error assembling message for sending
```
=> fix FAIL REGISTER INVALID_USERNAME case

irc/config.go
This is not especially sensitive and doesn't require a pointfix.
=> propagate require-sasl into tor-listeners.require-sasl

irc/server.go
Configurations with require-sasl and open account registration are valid,
but likely unintended. Show a warning about them.
=> add a warning for the #1634 case

default.yaml, irc/client.go, irc/config.go, irc/ircconn.go, irc/listeners.go, irc/server.go, traditional.yaml
This is somewhat irresponsible, but I know someone who patches this value out for a private server, and this would allow them to use official builds.
This is similar to `globalUtf8EnforcementSetting`; it's set on initial config load and can't be modified subsequently, so the application code can read it without any data race.
=> make MaxLineLen configurable

irc/client.go, irc/znc.go
This is a regression introduced in 0d05ab4ff4249f (so it doesn't get a changelog entry).
Thanks @mikaela and @kylef for finding this!
=> fix znc.in/playback for individual DM targets

irc/accounts.go, irc/nickserv.go
Users logged into an account can see their own email.
Opers with the accreg capability can see all users.
=> Show email in NS INFO when user has permission.

irc/chanserv.go
Commit 7ce396931cff32558112c65e1f9c93aacc5c7a1f introduced the ability
that every user with an account in the AMODE list of a channel can use
the OP command to restore their modes. Update the chanserv help message
accordingly.
=> update ChanServ OP command documentation

README.md
The AUR (arch linux user repository) link in the README.md was pointing to the AUR with the old name and was throwning a 404 error message. 
This PR changes it to the the right AUR package https://aur.archlinux.org/packages/ergochat/
=> Fixing the AUR package link in the README.md file

docs/MANUAL.md, irc/channel.go
=> Allow +v users to talk in +R channels.

irc/modes.go
Spotted these two numerics are missing the client parameter (which causes channel name to have the wrong index).
=> Include nick in ERR_LISTMODEALREADYSET and ERR_LISTMODENOTSET

irc/help.go
Forgot to add to the `snomaskHelpText` in `help.go`  when I had sent  #1728
=> fix missing disconnect sno help text

go.mod, go.sum, irc/accounts.go, irc/client.go, irc/config.go, irc/errors.go, irc/handlers.go, vendor/github.com/xdg-go/pbkdf2/.gitignore, vendor/github.com/xdg-go/pbkdf2/LICENSE, vendor/github.com/xdg-go/pbkdf2/README.md, vendor/github.com/xdg-go/pbkdf2/go.mod, vendor/github.com/xdg-go/pbkdf2/pbkdf2.go, vendor/github.com/xdg-go/scram/CHANGELOG.md, vendor/github.com/xdg-go/scram/LICENSE, vendor/github.com/xdg-go/scram/README.md, vendor/github.com/xdg-go/scram/client.go, vendor/github.com/xdg-go/scram/client_conv.go, vendor/github.com/xdg-go/scram/common.go, vendor/github.com/xdg-go/scram/doc.go, vendor/github.com/xdg-go/scram/go.mod, vendor/github.com/xdg-go/scram/go.sum, vendor/github.com/xdg-go/scram/parse.go, vendor/github.com/xdg-go/scram/scram.go, vendor/github.com/xdg-go/scram/server.go, vendor/github.com/xdg-go/scram/server_conv.go, vendor/modules.txt
Needs careful review to make sure it doesn't introduce an auth bypass.
=> implement SCRAM-SHA-256

irc/client.go
This is a bug in #1577 / 03185ea4a9547c8b. The intent was that if allow-truncation was enabled, lines over 512 bytes would be processed in their truncated form. Instead, they were being rejected and the client was being disconnected. (We were hitting the `else if err != nil` case at the bottom of the conditional.)
=> fix incorrect handling of overlong lines when allow-truncation is enabled

irc/nickserv.go
"LOGOUT ALL" logs out all clients for a user.
Fixes #1712.
=> Correct help text for NS CLIENTS LOGOUT.

irc/accounts.go, irc/handlers.go
reported by @Mikaela
Successful transcript made with irctest:
```
1628006140.243 1: connects to server.
1628006140.243 1 -> S: CAP LS 302
1628006140.243 S -> 1: :ergo.test CAP * LS :account-notify account-tag away-notify batch cap-notify chghost draft/account-registration draft/channel-rename draft/chathistory draft/event-playback draft/languages=1,en draft/multiline=max-bytes=4096,max-lines=32 draft/relaymsg=/ echo-message extended-join invite-notify labeled-response message-tags multi-prefix oragono.io/nope sasl=PLAIN,EXTERNAL,SCRAM-SHA-256 server-time setname userhost-in-names znc.in/playback znc.in/self-message
1628006140.243 1 -> S: CAP REQ :sasl
1628006140.243 S -> 1: :ergo.test NOTICE * :*** Looking up your hostname...
1628006140.243 S -> 1: :ergo.test NOTICE * :*** Found your …
```
=> fix SCRAM not supporting client IDs

irc/config.go
This is already implemented, but TARGMAX=KICK:1 says it isn't.
Instead, let's advertise that indefinitely many targets are allowed.
Refs:
* https://defs.ircdocs.horse/defs/isupport.html#targmax
* https://github.com/ircdocs/modern-irc/pull/112
This enables a test in https://github.com/ProgVal/irctest/pull/100 (which relies on TARGMAX to detect if the test should run)
=> Advertise support for multiple KICK targets

irc/handlers.go
For consistency with RFC2812, Bahamut, Hybrid, Insp, Plexus4, Unreal.
https://datatracker.ietf.org/doc/html/rfc2812#section-3.2.8
At the expense of consistency with chary/solanum, irc2, and ircu2.
Will be tested by irctest: https://github.com/ProgVal/irctest/pull/100
=> Make kick messages default to the kicker name instead of the kicked

irc/handlers.go
Refs:
* other instances in the codebase
* https://defs.ircdocs.horse/defs/numerics.html#err-needmoreparams-461
* https://modern.ircdocs.horse/#errneedmoreparams-461
irctest PR: https://github.com/ProgVal/irctest/pull/101
=> Add missing argument to ERR_NEEDMOREPARAMS on USER commands.

irc/client.go, irc/config.go, irc/histserv.go, irc/panic.go, irc/server.go, irc/utils/net.go
These changes are from my attempt to build reverse proxying of websockets into Ergo itself. I abandoned that in favor of a separate codebase, but this refactoring is still valid.
=> factor out some shared code

irc/accounts.go
Reported by @tacerus. This was most likely introduced by 8b2f6de3e.
=> fix spurious "corrupt account creds" logline

irc/mysql/history.go
It was sending MESSAGE_ERROR, which was inappropriate. Send an empty batch
for now (this is at parity with the in-memory implementation).
=> CHATHISTORY with nonexistent msgid should send empty batch

Dockerfile
See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2 ;
this maintains compatibility with older, buggy versions of docker and runc.
Alpine 3.13 is supported until 2022-11-01.
=> docker: downgrade alpine to 3.13 again

irc/modes.go
Reported by @Mikaela; normally this requires +o or higher on the
channel that is the target of the forward, but SAMODE should bypass
this check.
=> SAMODE +f shouldn't require channel privileges

irc/handlers.go
Reported by @mogad0n; the mute mask was being case-canonicalized,
but the RELAYMSG identifier wasn't being case-canonicalized before
the check.
=> fix casefolding issue in muting RELAYMSG

irc/nickserv.go
Fix #1828
Tested with both cases for `NS SUSPEND`
=> NS SUSPEND now req 'ban' capabs

distrib/docker/README.md, distrib/docker/docker-compose.yml, docs/MANUAL.md
In the main manual doc, and the Docker compose reference file, the image repo location appears to be out of date.
The former was referencing `oragono/oragono:latest` and the latter, `ergochat/ergo`, both on Docker Hub. Neither of those repos have seen a push in >= 6 months.
This PR updates both locations to be consistent with the Docker specific instructions at `distrib/docker/README.md`. I have updated both references to `ghcr.io/ergochat/ergo:stable` accordingly, and tested that the compose file deploys + the app functions:
```
$ podman-compose up -d
['podman', '--version', '']
using podman version: 3.4.3-dev
** excluding:  set()
podman pod create --name=ergo --share net --infra-name=ergo_infra -p 6667:6667/tcp -p 6697:6697/tcp …
```
=> Update docker repo location

.github/workflows/docker-image.yml
This PR adds support for building Docker container images for the `aarch64` (aka `arm64`) platform. Among other hardware targets, this will allow Ergo to be deployed on the AWS EC2 instance families running the ARM Graviton processor line.
See my [test run](https://github.com/erincerys/ergo/runs/4415128484?check_suite_focus=true) of this action here, and the [GHCR page of my fork](https://github.com/erincerys/ergo/pkgs/container/ergo) for proof of the additional platform.
Minor additional refactor:
- Build task descriptions prettified
- Environment variables created and referenced in action configuration aspects
- White space added for readability
=> Build arm64 container images

irc/client_lookup_set.go
It collides with the massmessage mask syntax. Reported by @emersion
=> disallow initial $ in nicknames

irc/handlers.go
Jobe points out that `0` is a valid oplevel in some contexts,
`*` is a better placeholder for "unimplemented".
=> send `*` for WHOX o (oplevel) instead of `0`

distrib/anope/anope2json.py
This resolves the Anope part of #1864, allowing for the automatic import of fingerprints for certfp authentication as part of a database conversion.
=> anope2json certfp support

irc/import.go
This should have been done in 8b2f6de3e0b9, since we updated both
the database schema and the importer then.
=> bump database version generated by importer

irc/handlers.go
Before, CAP LS responses after registration could actually be truncated:
```
:ircs.redacted.site CAP asdfasdfasdf LS :account-notify account-tag away-notify batch cap-notify chghost draft/account-registration=before-connect,email-required draft/channel-rename draft/chathistory draft/event-playback draft/extended-monitor draft/languages=1,en draft/multiline=max-bytes=4096,max-lines=24 draft/relaymsg=/ echo-message ergo.chat/nope extended-join invite-notify labeled-response message-tags multi-prefix sasl=PLAIN,EXTERNAL server-time setname userhost-in-names znc.in/playback znc.in/sel
```
After this change, in my testing, we can produce a CAP LS response of exactly 510 bytes (not counting the `\r\n`), then adding a single additional character to the nickname pushes a token onto the next line: …
=> correctly account for nickname in CAP LS arithmetic

irc/nickserv.go
Previously, daemon would compare `newPassword` which got changed from `"*"` to `""` to `params[2]` which did not get changed.
=> Fix #1883 Nickserv gives error when user attempt to change password to *

README.md, distrib/openrc/ergo.confd, distrib/openrc/ergo.initd
Written originally for Gentoo but should work
on Alpine and other OpenRC-consuming distros too.
Signed-off-by: Sam James <sam@gentoo.org>
=> distrib: add OpenRC init scripts

irc/handlers.go
This extends #1650 to cover WHO as well as WHOIS
=> show arbitrary IP in WHOX

distrib/openrc/ergo.confd, distrib/openrc/ergo.initd
- Add logging to init script
- Add delay so OpenRC realises if we crashed quickly b/c of e.g. bad config
file
- General cleanups (like supporting multiple instances, style changes)
This should make it a lot easier to see what's going wrong when something
breaks.
Bug: ergochat/ergo#1914
Signed-off-by: Sam James <sam@gentoo.org>
=> distrib: refine OpenRC init scripts

default.yaml, traditional.yaml
Discussed with emersion, this is the value used in soju and it works fine.
=> bump recommended CHATHISTORY limit to 1000

irc/handlers.go
As discussed in #1911 this replicates the intended behavior in which the daemon does list a channel with mode +s in `quote list` if the user is joined to that channel.
=> Fix #1911 +s channels don't appear in /list even though on the channel

irc/accounts.go
DEFCON 4 and lower were blocking SAREGISTER. This is wrong; admins should be
allowed to make new accounts even under DEFCON (this may be needed
specifically to work around the DEFCON restriction).
=> make SAREGISTER override DEFCON

irc/histserv.go
Fixes #1881 . As per discussion with @slingamn on irc, this is fixed by requiring two parameters for all cases, instead of allowing one parameter for cases when persistent database storage is used. Also deleted the extra logic for number of params at the beginning of histservDeleteHandler which is now not necessary.
Also modified the bits of help to represent the target param as necessary ([] -> <>). Let me know if I missed anything else, thank you.
=> histserv delete now requires two params

irc/getters.go, irc/server.go, irc/utils/config.go
I verified that this produces the same ASM.
Before:
```
server.go:319         0x84b1b7                90                              NOPL
getters.go:19         0x84b1b8                488b90f0000000                  MOVQ 0xf0(AX), DX
getters.go:19         0x84b1bf                48899424b8000000                MOVQ DX, 0xb8(SP)
```
After:
```
server.go:318         0x84b1d7                90                              NOPL
getters.go:18         0x84b1d8                488b90f0000000                  MOVQ 0xf0(AX), DX
config.go:27          0x84b1df                48899424b8000000                MOVQ DX, 0xb8(SP)
```
Not really happy with the name `ConfigStore`, alternative suggestions welcome :-)
=> genericize atomic config changes

irc/handlers.go
Solves #1943 
I didn't do much except allow the condition for when `info.Duration=0` in formatban function.
I have tested it locally.
=> /UBAN LIST explicitly states 'indefinite' durations for Klines/Dlines 

irc/client.go, irc/getters.go, irc/logger/logger.go, irc/mysql/history.go, irc/server.go, irc/usermaskset.go
See 69448b13a10a14517 / #1969; the compiler can now ensure that a uint64
intended for atomic access is always aligned to a 64-bit boundary.
Convert atomic operations on uint32s and pointers as well.
=> use new aligned atomic types everywhere

default.yaml, irc/client.go, irc/config.go, irc/fakelag.go, irc/fakelag_test.go, traditional.yaml
This is #1978. I merged instead of squashing so I forced master to undo it (naughty).
=> exempt a configurable number of MARKREAD commands from fakelag

irc/config.go
Kiwi expects it due to https://github.com/kiwiirc/kiwiirc/pull/1244 , but the corresponding spec change only altered the cap name, not the 005 name.
=> re-add draft/CHATHISTORY 005

README.md, default.yaml, traditional.yaml
See discussion on #1718.
I want to do this in the 2.11 bugfix release unless there is strong pushback. PRECIS will remain fully supported, it just won't be the recommended default anymore.
=> change default casefolding to ascii

irc/utils/signals_plan9.go, irc/utils/signals_windows.go
This is a bug from #2014 that was breaking compilation for Windows.
=> don't reference SIGUSR1 on windows

irc/nickserv.go
Currently the `SAREGISTER` command short help appears twice in `/ns help`, and `SAVERIFY` is not listed. Short help is copy-pasted from long help.
=> Fix SAREGISTER short help in SAVERIFY command

Makefile
Disable dynamic linking by default. We have the whole release cycle to evaluate whether this causes problems (I don't anticipate any).
=> Fix #2023 (disable dynamic linking by default)

.goreleaser.yml
Follows up from #2025. Fixes:
```
⨯ release failed after 5.75s error=failed to build for darwin_arm64: exit status 2: # runtime/cgo
gcc: error: unrecognized command-line option '-arch'
```
with goreleaser 1.0.0 and go 1.19.4.
=> disable cgo for goreleaser

gencapdefs.py, irc/caps/defs.go
Requesting this capability will not change Ergo's behavior, since we've always sent standard replies to users unconditionally.
=> add standard-replies capability

irc/client.go, irc/listeners.go, irc/utils/proxy.go
Also stop attaching the *tls.Config to the wrapped connection, since this forces it to be retained beyond its natural lifetime.
=> make ReloadableListener lock-free

default.yaml, irc/config.go, traditional.yaml
cc @jwheare
IRCCloud attempts SCRAM-SHA-256 when it is advertised and does not fall back to PLAIN on failure. This will break authentication for accounts that were created on Ergo 2.7 or earlier, then never logged into again until the first time SCRAM-SHA-256 was advertised (because we only have bcrypt-based credentials and no SCRAM credentials). This is an unacceptable compatibility break, but it's also a weird enough edge case that IRCCloud will probably never fix it.
Compromise: make advertising it a recommended default, but require old servers to opt in explicitly. On a related note, [SCRAM is bad and clients should not implement it](https://gist.github.com/slingamn/3f2fed196df5ef14d1316a1ffa9d59f8).
Fixes #1782
=> recommended default: advertise SCRAM

.github/workflows/build.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> bump github actions

.github/workflows/docker-image.yml
Should fix https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ ?
=> bump docker actions

irc/accounts.go, irc/bunt/bunt_datastore.go, irc/channel.go, irc/channelmanager.go, irc/channelreg.go, irc/chanserv.go, irc/database.go, irc/datastore/datastore.go, irc/errors.go, irc/getters.go, irc/handlers.go, irc/hostserv.go, irc/import.go, irc/legacy.go, irc/nickserv.go, irc/serde.go, irc/server.go, irc/utils/uuid.go
This is pretty complicated and touches a lot of things, so I'm interested in reviews, maybe from @ajaspers or @progval ?
The core idea here is to refactor persistence to eventually support datastores other than buntdb. There are two problems:
1. We don't want typical chat operations to block on the datastore (this is mostly implemented already, with the asynchronous persistence / `markDirty` stuff, but there are some cases where we would still block, particularly for accounts where every login currently incurs a read from the datastore)
2. We don't want to require nontrivial consistency guarantees from the datastore
The new approach is best illustrated by the new, weak datastore API:
https://github.com/slingamn/ergo/blob/7ce06362764ee35629521eacc1fdee5405370efd/irc/datastore/datastore.go …
=> refactor of channel persistence to use UUIDs

CHANGELOG.md, irc/ircconn.go, irc/version.go
I assumed gorilla validated UTF8 for incoming text messages. In fact, the
documentation states:
>It is the application's responsibility to ensure that text messages
>are valid UTF-8 encoded text.
and this applies to both incoming and outgoing messages. Consequently,
even when enforce-utf8 is enabled, it was possible to send invalid UTF8
to Ergo inside a websocket text frame. This data would be incorrectly
considered valid UTF8, and could be relayed to other clients, including
to websocket clients inside a text frame. The resulting frame would violate
the websocket protocol, causing web clients to be disconnected.
=> pointfix for websocket client DoS

irc/ircconn.go
This is #2037 (an optimization) plus a correctness issue that should get a changelog entry.
=> tweaks to websocket handling

gencapdefs.py, irc/caps/defs.go, irc/client.go, irc/client_lookup_set.go, irc/commands.go, irc/getters.go, irc/handlers.go, irc/nickname.go
Also clean up some subtleties in auto-away aggregation.
=> implement draft/pre-away

default.yaml, irc/email/email.go, irc/smtp/smtp.go, traditional.yaml
=> support implicit TLS for mail submission agents

Makefile, default.yaml, gencapdefs.py, irc/caps/defs.go, irc/commands.go, irc/handlers.go, irc/help.go, irc/histserv.go, traditional.yaml
Permission to use REDACT mirrors permission for 'HistServ DELETE'
Spec: https://github.com/ircv3/ircv3-specifications/pull/524 (this is a variant of https://github.com/ircv3/ircv3-specifications/pull/425 with only deletion/redaction, and targetmsg moved from a tag to a parameter)
Tests: https://github.com/progval/irctest/pull/203
@slingamn Thoughts on this design before I add support for PMs?
=> Implement draft/message-redaction

irc/caps/set.go, irc/caps/set_test.go
This is more or less explicitly prohibited by the spec:
https://ircv3.net/specs/extensions/capability-negotiation.html#multiline-replies-to-cap-ls-and-cap-list
See https://github.com/progval/irctest/pull/205 ; #2065 here caused the CAP LS 301 response to spill onto two lines, breaking SASL in irssi and possibly other clients.
=> don't send multiline responses to CAP LS 301

Dockerfile
The base golang image ships with some packages pre-installed, but they're not necessarily the latest. If we try to add a package that (transitively) depends on one of the existing ones, it'll fail if it's expecting a newer version.
To address this, simply `apk upgrade` before trying to `apk add`.
Closes #2071
=> Dockerfile: `apk upgrade` before `add`

distrib/apparmor/ergo
Hi,
this adds the AppArmor profile I ship with with the openSUSE package. It should work just as well on any other distribution.
=> Import AppArmor profile

gencapdefs.py, irc/caps/defs.go, irc/channel.go, irc/handlers.go
https://github.com/ircv3/ircv3-specifications/pull/527
=> implement draft/no-implicit-names

distrib/docker/README.md
tagging @csmith as our resident Docker expert :-p
It seems like this fixes #2096 ( unreaped zombies when using an auth-script or ip-check-script that spawns its own subprocesses, then exits before reaping them), and has basically no downside. Thoughts?
=> add --init to suggested docker run invocations

docs/MANUAL.md
I wasn't sure what would be the preferred method to document this, but the existing reverse proxy documentation only applies to the IRC socket. Although the documentation does make it pretty obvious it will break reverse-proxied HTTP, I thought it might be helpful to document the correct way to do this, since I struggled with it.
=> Explain reverse proxy setup for websockets

irc/isupport/list.go
Just a documentation change effectively
=> pull out max parameters constant in isupport impl

default.yaml, irc/client.go, irc/gateways.go, irc/handlers.go, irc/server.go, traditional.yaml
See #1686; this allows i2pd to pass the i2p address to Ergo, which may be useful for moderation under some circumstances.
=> add a config switch to accept hostnames from WEBIRC

irc/handlers.go
We were checking the login throttle at the beginning of every SASL conversation. This had several problems:
1. Pidgin (on Windows?) tries every mechanism in order, regardless of the CAP advertisement. It would use up the default throttle allowance trying unsupported mechanisms like CRAM-MD5.
2. The throttle was actually checked twice for AUTHENTICATE PLAIN (once at the start of the conversation and once in AuthenticateByPassphrase).
The general pattern here is that we should check the throttle every time we do something "expensive" (bcrypt verification, send a reset email) or "dangerous" (anything that could lead to a bruteforce attack on passwords). Therefore, delete the check from the AUTHENTICATE handler, and add one at the beginning of the SCRAM conversation to replace it.
=> fix login throttle handling

irc/modes.go
cc @DanielOaks and @progval for thoughts. The last time we revisited this was probably #649. This change has the following effects:
1. We still send `RPL_CHANNELMODEIS` and `RPL_CREATIONTIME` for `MODE #chan` (standard behavior)
2. We still send them for `MODE #chan i` (most ircds translate this into +i, but it shouldn't matter)
3. We still send them for `MODE #chan +i` when it is a no-op because `+i` was already enabled (most ircds will send nothing)
4. We **no longer** send them for `MODE #chan +o nick` when it fails or is a no-op
5. We do not send them for `MODE #chan b` (standard behavior, fixed in Ergo by #649)
6. The handling of `+k` and similar modes that take an argument is not changed (the operation is always broadcasted even when it is a no-op)
=> clean up RPL_CHANNELMODEIS logic

default.yaml, traditional.yaml
Insp and Libera use 100, seems a bit safer
=> lower recommended ban list limit to 100

ergo.go
`ergo defaultconfig` (#2157, #2160) required a valid config file in order to run, making it somewhat useless ;-)
=> don't require a config file for defaultconfig

irc/channel.go, irc/handlers.go
* The message target was not being counted :-(
* The additional character added to the target by STATUSMSG was not counted
This will break irctest, but the irctest is actually wrong: https://github.com/progval/irctest/pull/281
=> fix truncation check

.goreleaser.yml, Makefile
Not for the 2.14 cycle, but posting the PR for later
=> update to goreleaser v2

irc/flock/flock.go, irc/flock/flock_unsupported.go
This enables cross-compilation from Linux with: `GOOS=solaris GOARCH=amd64 make build`
=> enable building for solaris

irc/handlers.go
It's too small anyway so the runtime has to reallocate it.
=> remove GCStats.Pause initialization

irc/config.go
https://modern.ircdocs.horse/#safelist-parameter
LIST is implemented via blocking (*ResponseBuffer).Send, so it can never exceed the sendq limit.
@delthas points out that this token is not especially useful to clients:
1. If it is not advertised, it probably means that the server is not aware of it, not that LIST is unsafe
2. It's not really actionable because the only thing the client can do is to not send LIST at all, which seems unreasonable
=> advertise SAFELIST

distrib/docker/README.md
Two small fixes to the Docker directions
- Add missing `--name ergo` to 'Persisting data' examples
- The command `pwd` is lowercase and linux is case sensitive. I think the line confused it for `$PWD` the environmental variable but the existing `$(PWD)` runs the PWD command and throws `-bash: PWD: command not found` on linux
=> Improve Docker "Persisting Data" Section

ergo.go
We should also set up a redirect covering the old link.
=> fix download link

irc/client.go, irc/getters.go, irc/nickserv.go, irc/server.go
getPushSubscriptions() could have a stale view of the latest subscription renewal and successful push times. We don't want to rebuild on every renewal or every push, so add a boolean refresh argument that controls rebuilding.
=> fix buggy persistence of push timestamps

irc/client.go
Introduced by #2218, reported by knolle
This does not need a changelog entry since it was never in a stable release; however, we should get an irctest that covers KILL
=> fix panic on KILL

irc/client.go, irc/server.go
Block uses of the JS Fetch API to send HTTP message bodies that are also valid IRC. The constraint on such messages is that they must begin with a valid HTTP verb; we can detect this and reject them immediately.
=> block HTTP DoS attacks

irc/isupport/list.go, irc/server.go
* Limit the payload to 380 bytes instead of 400
* Don't translate the final parameter
This leaves about 60 bytes for the server name.
=> safer 005 length limits

irc/handlers.go, irc/server.go
* Clamp CHATHISTORY timestamp selectors to be in [0, MaxInt64]
* Convert everything to UTC up front (probably a no-op)
=> improve robustness of timestamp parsing

irc/caps/constants.go
I missed this in the back-and-forth on https://github.com/ircv3/ircv3-specifications/pull/543
cc @emersion
=> fix isupport batch name

default.yaml, gencapdefs.py, irc/caps/defs.go, irc/channel.go, irc/channelreg.go, irc/client.go, irc/commands.go, irc/config.go, irc/getters.go, irc/handlers.go, irc/help.go, irc/metadata.go, irc/metadata_test.go, irc/numerics.go, irc/utils/chunks.go, traditional.yaml
adds support for most of the draft/[metadata-2](https://www.youtube.com/watch?v=Sr57Je1fVvM&t=18s) spec
fixes #1745
what's new:
* a new draft/metadata-2 cap
* the metadata command, with SET, GET, CLEAR, LIST, SUB, UNSUB, SUBS & SYNC
* a `metadata` section in the config
what's missing:
* before-connect
* visibility controls. as of right now everything is * 
* any attempt at rate limiting
* postponed synchronisation
this is a draft because i still need to write some tests but i thought i'd open a pr so someone can tell me if i've done something egregiously wrong (this is my first time doing anything particularly substantial in go (!!!!))
=> metadata-2

default.yaml, irc/channel.go, irc/channelmanager.go, irc/config.go, irc/errors.go, irc/getters.go, irc/handlers.go, irc/help.go, irc/metadata.go, irc/server.go, traditional.yaml
cc @thatcher-gaming, possibly of interest (no pressure)
This addresses some of #2274. One area where I am not satisfied is how the spec interacts with persistent clients ("always-on"):
1. I don't like the aspect of the current spec where it does an edge-triggered metadata sync on requesting the cap; I generally prefer explicit client commands to having `CAP REQ` trigger side effects
2. Instead, for always-on clients, we preemptively send them their own metadata in the registration burst, between 005 and RPL_ENDOFMOTD / ERR_NOMOTD. (In the spirit of the current spec, we might want to send even non-always-on clients that have requested the cap an empty batch here? Although if the batch is empty, you don't know what entity the empty batch is talking about --- really you need labeled-response …
=> round 1 of follow-up for metadata

irc/help.go, irc/strings.go
Fix a couple things that were documented incorrectly.
This fixes #2278. I don't think it's worth restoring `HISTORY me` or `HISTORY *` since it would require some refactoring and I see no evidence that the feature is useful.
=> fix some documentation
