CHANGELOG.md, irc/commands.go, irc/help.go, irc/server.go
This is just a basic implementation and only works for a single server
=> LUSERS command

irc/client.go
=> server-time: convert local time to UTC before using it

CHANGELOG.md, irc/client.go, irc/commands.go, irc/help.go, irc/server.go, irc/util.go
UPDATE: Solved the trailing issue on the latest rev
=> USERHOST command

README.md
Section on any links that are aggregated for platform builds that are alternatively available from release downloads/source
=> Platform specific packaging information

README.md
an area showing that you can run oragono with a different config (which is great, thank you!) and that you can configure the yaml as well to change paths (I didn't want to enumerate all the settings, but the awareness of such is hopefully useful to others!)
=> example of running with a config

Makefile
See the individual commit comments
=> A couple minor make tweaks

.travis.yml, Makefile, README.md
this would be a jump start for #96 
* runs `make` which hits all the targets
* svg in the README/markdown to show current status (it should be pointed properly for you)
someone who can configure this in travis for the project would have to enable it and then this should "just work"
=> simple travisci definition

irc/server.go
Close the client's connection if we're unable to parse their IP.
This also simplifies the check to reduce indentation by a level.
Finally, this replaces the two-var construction of the pseudo-const
messages with an inline dereference via a slice to allow constructing
them less noisily.
Note: this is easier to review if you squash whitespace (via adding `?w=1` to github's diff viewer url).
I don't know of any way to actually hit that error case, but if we're intent on handling the error, this is a slightly neater way to do so.
=> server: close connection on parse-ip failure

irc/client.go
Thanks for the very descriptive TODO :-)
=> send the actual quit message to friends

irc/dline.go, irc/kline.go
* Synchronize map accesses
* Be more aggressive about cleaning up expired lines; this is now done in a separate goroutine, after the original read-only function call has returned
* CIDR dlines did not work (nil dereference of `addrInfo` instead of `netInfo`)
=> refactor [dk]linemanagers

irc/channel.go
This is a better version of #159. The technique here is analogous to what I'm planning to use for the database layer. The diff is noisy because of `gofmt`; here's [git show -w](https://gist.github.com/slingamn/9058ede347293de4bf399312dfb620f3) of the commit.
=> fix a race in regenerateMembersCache

irc/modes.go
Anyone could change channel modes, as long as they *weren't* an ircop ;-)
=> fix channel mode change privilege enforcement

irc/idletimer.go
Sorry I'm making you review yet another one of these :-)
Basically, the approach of sleeping on a dedicated goroutine was creating more problems than it solved. This version uses `time.AfterFunc`. Hopefully the state transitions are clearer.
=> refactor idle timeouts again

irc/server.go
Seems like we might as well include this fix for now and figure out the standardization question later.
=> partial fix for #217

oragono.go
when entering/generating the password it's helpful to at least be asked to confirm the input so if you get something like an extraneous character, on confirmation, you could catch that
=> genpasswd confirmation of entered password

docs/MANUAL.md
how do you do let's encrypt? let's move this from an issue to the FAQ, this probably takes care of #118 and #231 well enough to at least resolve them and start using the md/docs going forward
=> FAQ Section: Let's Encrypt

docs/MANUAL.md
Just taking care of a couple things that were discussed on #232.
=> more tweaks to letsencrypt documentation

irc/channel.go, irc/channelmanager.go, irc/channelreg.go, irc/chanserv.go, irc/database.go, irc/getters.go, irc/handlers.go, oragono.go
1. Implement persistent channel keys (#208)
2. Persist changes to registered channel modes
3. Backend changes for persisting operator status (partial #198)
=> Updates to channel persistence

DEVELOPING.md
I'm just going to merge this, shouldn't be a big deal.
=> update developing documentation

irc/channel.go, irc/channelmanager.go, irc/commands.go, irc/handlers.go, irc/help.go, oragono.yaml
This is an update of #267 incorporating the review feedback; it changed enough that I thought it would be worth restarting the history from scratch.
=> implement SAJOIN, allow channel founders to join unconditionally

irc/channel.go, irc/channelreg.go, irc/chanserv.go, irc/getters.go, irc/server.go
Not much to it. The massive change to the `Server` struct is just the deletion of `channelRegistrationEnabled`, plus `gofmt` noise.
=> add CHANSERV UNREGISTER

irc/utils/bitset.go
=> simplify CAS logic a bit

irc/client.go
Should fix #286. I think the invisible count is probably correct.
=> fix miscounting in LUSERS

irc/server.go
Raw message: `@time=2018-08-17T15:47:16.636Z :oragono.test 330 shivaram_hexchat netcat_ netcat :is logged in as`
Hexchat displays this as: `* [netcat_] is logged in as netcat`
=> Fix a bug in 330 RPL_WHOISACCOUNT

irc/hostserv.go
Reported by bogdomania on freenode.
=> fix hostserv help string

irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/commands.go, irc/handlers.go, irc/isupport/list.go, irc/isupport/list_test.go, irc/logger/logger.go, irc/server.go, oragono.go
Mostly explained in the commit messages.
re. logging timestamps: someone was debugging an issue that turned out to be client-imposed send delays. The debugging process was impeded by oragono's log only offering second resolution for logline timestamps, hence the upgrade to millisecond resolution.
=> eight small changes

Makefile, irc/accounts.go, irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/config.go, irc/connection_limits/throttler.go, irc/connection_limits/throttler_test.go, irc/errors.go, irc/getters.go, irc/handlers.go, irc/idletimer.go, irc/logger/logger.go, irc/nickname.go, irc/nickserv.go, irc/server.go, irc/whowas.go, irc/whowas_test.go, oragono.yaml
These are probably best reviewed individually. We've got:
1. A couple of pointless optimizations related to logging
1. Some refactoring
1. A couple of bug fixes, one for a bad bug involving unsuccessful nickname changes that was introduced in 52b0fb71e78
1. A new feature: login throttling (for #280)
1. A new feature: customizable nickname enforcement (for example: the server can default to timeout-based enforcement, but users can opt in to strict enforcement)
=> some more changes

irc/nickserv.go
including the bug reported by @adrianuswarmenhoven on #221.
=> two service bug fixes

README.md
The README mentions that a Dockerfile was contributed in the credits but there are no other references to Docker in the repo, which mightily confused me!
=> Add docker info to README

irc/caps/set.go, irc/caps/set_test.go, irc/handlers.go, irc/utils/bitset.go, irc/utils/bitset_test.go
Passes irctest, tested the bugfix manually (the bug should get an irctest regression test though).
=> correctly support disabling caps with CAP REQ, fixes #337

irc/client.go, irc/handlers.go
Just wanted to deduplicate the slicing/validation logic.
=> simplify username logic

irc/getters.go
=> Fix usernames being used in place of hostnames.

irc/channel.go
Fixes #353.
(I thought I'd put up the PR now since it's so simple, we can keep discussing on #353 whether we actually want to make the change.)
=> don't send the client its own on-join MODE line

irc/help.go
=> fix typo in CHATHISTORY help url

CHANGELOG.md, docs/MANUAL.md, irc/accounts.go, irc/errors.go, irc/handlers.go, irc/nickserv.go, irc/server.go, oragono.yaml
Mostly stuff we already discussed.
Feel free to make further changes to either the manual or changelog according to taste (obviously).
The race condition in c8cf0befc6c816 was introduced in a0bf548fc56839, so it was never present in the stable branch :-p
=> changelog and manual updates, plus some last-minute fixes

irc/channel.go, irc/handlers.go, irc/modes.go
bogdomania reported (I didn't file a separate issue for this one):
1. KICK without privileges incorrectly returned ERR_CANNOTSENDTOCHAN
2. Halfops should be able to kick voice and unprivileged, but not other halfops
csmith reported #374 and #375
=> fix another three bugs that were reported today

irc/nickname.go, irc/responsebuffer.go
"Address" because I don't want GitHub to close it :-)
=> address #391

CHANGELOG.md, README, docs/MANUAL.md, docs/MOTDFORMATTING.md
=> Changelog updates

install.sh
`shellcheck` is happy with this now.
=> fix bashisms in install.sh

irc/idletimer.go
https://bugs.torproject.org/29665 describes how single-onion circuits
will close unless the client sends data every 60 seconds. To cause the
client to send these messages, have Oragono send the client a PING every
30 seconds.
=> work around a Tor bug

irc/channel.go, irc/client.go, irc/commands.go, irc/handlers.go, irc/modes.go, irc/nickname.go
I didn't integrate the roleplay code because it has more edge cases, seems fine to keep it off to the side for now.
=> fix #425 and #395

irc/channel.go, irc/semaphores.go, irc/socket.go, irc/utils/semaphores.go
No point, I just like showing this to people and it's easier if it's separated from the application code :-)
=> extract Semaphore to utils package

irc/handlers.go
This issue *might* have problematic security implications but I don't think it's worth worrying too much about them.
=> disallow AUTHENTICATE when already auth'ed

docs/MANUAL.md, irc/channel.go, irc/client.go, irc/handlers.go, irc/nickname.go
I think Mozilla used to call these bugs "papercuts"?
=> three QoL fixes

irc/client.go
=> send command processing errors to the originating session only

gencapdefs.py, irc/caps/defs.go, irc/channel.go, irc/client.go, irc/commands.go, irc/handlers.go, irc/help.go, irc/misc_test.go, irc/znc.go
Fixes #486 
This is kind of a toy but it might actually be useful to real-world users, since it has a certain amount of client support (I tested it in Textual).
=> support znc.in/playback

irc/accounts.go, irc/client_lookup_set.go, irc/errors.go, irc/nickname.go, irc/services.go
=> check restricted nicknames against skeletons, more pedantically

irc/nickname.go
=> Check restricted nicknames against skeletons

gencapdefs.py, irc/caps/defs.go, irc/client.go, irc/responsebuffer.go
Not for merge yet, since it's missing the window for v1.1.0.
=> upgrade to draft/labeled-response-0.2

irc/handlers.go
1. Your own snomasks would be reported as belonging to the other user
2. Prefixes were incorrect
=> fix bugs affecting SAMODE on other users

irc/accounts.go
=> fix spurious error message

CHANGELOG.md, Gopkg.lock, irc/constants.go
Action items:
* Think about whether we missed any cases
* Merge this into stable
* I'll tag it and go through the normal release workflow
=> release branch for v1.1.1

.travis.yml
=> upgrade golang to 1.13

irc/strings.go, irc/strings_test.go
=> remove unnecessary special-casing for ASCII

irc/client.go, irc/config.go, irc/gateways.go, irc/server.go, oragono.yaml
I'm happier with this implementation.
=> fix #561, take two

irc/accounts.go, irc/channel.go, irc/channelmanager.go, irc/channelreg.go, irc/chanserv.go, irc/client.go, irc/errors.go, irc/handlers.go, irc/hostserv.go, irc/modes.go, irc/nickserv.go, irc/types.go
* Fix #684
* Fix #683
* Add `CHANSERV CLEAR`
* Allow mode changes from channel founders even when they aren't joined
* Operators with the chanreg capability are exempt from max-channels-per-account
* Small fixes and cleanup
=> chanserv enhancements and miscellaneous fixes

irc/accounts.go, irc/chanserv.go
bogdomania reported that this was confusing.
=> better UX for cancelling channel transfers

gencapdefs.py, irc/accounts.go, irc/caps/defs.go, irc/chanserv.go, irc/client.go, irc/commands.go, irc/config.go, irc/database.go, irc/errors.go, irc/gateways.go, irc/handlers.go, irc/legacy.go, irc/nickserv.go, irc/utils/crypto.go, irc/utils/crypto_test.go, oragono.yaml
I ended up removing `ACC` rather than updating it.
There are a lot of potential edge cases here with the possibility of an authentication bypass. I think I tested them all. Maybe @csmith could review?
=> fix #530, #721

irc/accounts.go, irc/config.go, irc/hostserv.go, oragono.yaml
You might want to review the user interface (as in, the new hostserv commands "offerlist", "take", "forbid", and "permit").
=> add support for offering vhosts

irc/accounts.go
For irctest compatibility.
Fixes #775
=> raise passphrase length limit to 300 bytes

irc/server.go
I didn't actually test this code path, so it was unsurprisingly buggy.
=> fix handling of history grace periods

irc/accounts.go, irc/channel.go, irc/client.go, irc/client_lookup_set.go, irc/commands.go, irc/getters.go, irc/idletimer.go
I don't entirely trust myself to evaluate the correctness of this change right now; I'll probably sleep on it.
=> change "last signoff" tracking to "last seen"

CHANGELOG.md, oragono.yaml
=> final changelog and documentation updates

go.mod, go.sum, irc/client.go, vendor/github.com/goshuirc/irc-go/ircmsg/message.go, vendor/modules.txt
=> upgrade irc-go, force 353 RPL_NAMREPLY to use a trailing

irc/modes/modes_test.go
/me is definitely not stealing those tests
=> irc/modes: remove duplicate test case

oragono.yaml
=> make +i the recommended default usermode

conventional.yaml, oragono.yaml
=> use 8097 as the example websocket port

irc/server.go
I realized the recreation on failure to reload was redundant; I can just delete the listener and it'll be recreated later (along with the other newly configured listeners).
=> simplify listener rehash logic

conventional.yaml, irc/mysql/config.go, irc/mysql/history.go, oragono.yaml
This adds a new configuration option, socket-path, instead of using
host.
=> Add support for Unix domain sockets.

irc/handlers.go, irc/server.go
=> make it clearer when rehash has completed

conventional.yaml, irc/accounts.go, irc/client.go, irc/client_lookup_set.go, irc/config.go, irc/getters.go, irc/handlers.go, irc/modes.go, irc/nickname.go, irc/nickserv.go, oragono.yaml
Persist user modes (#819), auto-away (#824), fix #1035 (found during testing).
=> last round of feature changes

irc/utils/args.go, irc/utils/args_test.go
=> Fix issue with one-character args in ArgsToStrings.

CHANGELOG.md
I'm basically ready to release 2.1.0 after this.
=> add changelog entries

irc/services.go
=> handle CTCP VERSION, PING and TIME for services pseudo-users

irc/getters.go
Deleting from a nil map is fine.
=> fix disabling of autoreplay-missed

irc/accounts.go, irc/client.go, irc/getters.go, irc/server.go
Also fix a bug where unregister didn't delete the stored user modes.
=> tweaks to lastSeen persistence

conventional.yaml, default.yaml, irc/accounts.go, irc/channel.go, irc/channelmanager.go, irc/client.go, irc/commands.go, irc/getters.go, irc/handlers.go, irc/help.go, irc/server.go
This ended up being pretty straightforward. I didn't special-case Tor connections (since they can be banned/excepted by hostmask).
=> fix #328 (implement DEFCON)

irc/nickserv.go
Just remembered someone getting confused by this.
=> alias for NICKSERV SET PASSWORD

CHANGELOG.md, DEVELOPING.md
I'll leave this open over the next week and push documentation updates to it.
=> documentation updates for release

irc/client.go, irc/config.go, irc/errors.go, irc/gateways.go, irc/ircconn.go
Someone requested this for a private server they're setting up.
=> make it easier to patch out the maximum line length

irc/ircconn.go
Websocket listeners would process an arbitrary number of invalid
(non-text or blank) messages without throttling. This imposes fakelag
on such messages by treating them as blank lines.
=> mitigate a potential DoS against websocket listeners

conventional.yaml, default.yaml, irc/config.go
These should have been removed in #1027.
Thanks @mogad0n!
=> remove stray references to timeout enforcement

CHANGELOG.md
=> changelog for v2.3.0

irc/handlers.go
=> PONG param 0 should be server name

conventional.yaml, default.yaml, irc/accounts.go, irc/authscript.go, irc/client.go, irc/config.go, irc/gateways.go, irc/script.go, irc/semaphores.go, irc/server.go
See discussion on #68.
This is a squash of #1263.
=> scripting API for IP bans

irc/client.go, irc/getters.go, irc/nickserv.go
CLIENTS LIST shows information about clients attached to a nick.
CLIENTS LOGOUT allows individual (or all) sessions to be logged out.
SESSIONS is now an alias for CLIENTS LIST.
Fixes #1072.
=> Add NickServ "CLIENTS LIST" and "CLIENTS LOGOUT".

docs/MANUAL.md, irc/channel.go, irc/config.go, irc/help.go, irc/modes.go, irc/modes/modes.go, irc/roleplay.go
=> Add +M (only registered/voice can speak) chanmode.

irc/nickname.go
This was found as part of the initial investigation of #1277.
=> fix channel history recorded for SANICK

irc/utils/net.go
```
:NickServ!NickServ@localhost NOTICE bbbbb :Connection:  /tmp/oragono <-> @ [pid=1807527, uid=1000]
```
=> output unix socket credentials where applicable

irc/utils/net.go, irc/utils/net_linux.go, irc/utils/net_nonlinux.go
=> fix non-linux builds

irc/modes.go, irc/modes/modes.go
=> actually enable the +T no-ctcp umode

Makefile, distrib/atheme/atheme2json.py, go.mod, go.sum, irc/accounts.go, irc/channelreg.go, irc/database.go, irc/import.go, irc/legacy.go, irc/migrations/legacy.go, irc/migrations/passwords.go, irc/migrations/passwords_test.go, oragono.go, vendor/github.com/GehirnInc/crypt/.travis.yml, vendor/github.com/GehirnInc/crypt/AUTHORS.md, vendor/github.com/GehirnInc/crypt/LICENSE, vendor/github.com/GehirnInc/crypt/README.rst, vendor/github.com/GehirnInc/crypt/common/base64.go, vendor/github.com/GehirnInc/crypt/common/doc.go, vendor/github.com/GehirnInc/crypt/common/salt.go, vendor/github.com/GehirnInc/crypt/crypt.go, vendor/github.com/GehirnInc/crypt/internal/utils.go, vendor/github.com/GehirnInc/crypt/md5_crypt/md5_crypt.go, vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go, vendor/modules.txt
1. `python3 distrib/atheme/atheme2json.py atheme.db output.json`
1. (Prepare an oragono `ircd.yaml` config file, but don't create a db file)
1. `oragono importdb output.json`
1. `oragono run`
=> first draft of atheme migration code

irc/handlers.go, irc/nickserv.go
=> review fix for #1308

docs/MANUAL.md
I have deliberately left out +E (Roleplaying) as I was advised it was depreciated and I am not comfortable with the concept yet
=> update MANUAL.md with toc links, some umodes, and some language

DEVELOPING.md, irc/config.go, irc/modes/modes.go, irc/modes/modes_test.go, irc/server.go
`CHANMODES=Ibe,k,l,CEMRUimnstu`
=> add +u and +U to CHANMODES token

irc/strings.go, irc/strings_test.go
=> validate normalized masks as IRC params

irc/handlers.go
Address SETNAME UX problems reported by @KoraggKnightWolf in #oragono:
1. No feedback by default on success or failure
2. Multi-word realnames are not correctly interpreted by some clients
=> enhancements to SETNAME

default.yaml, irc/channel.go, irc/client.go, irc/commands.go, irc/config.go, irc/handlers.go, irc/help.go, traditional.yaml
=> security enhancements for INVITE

.travis.yml
https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
=> explicitly whitelist branches for building

irc/accounts.go, irc/errors.go, irc/getters.go, irc/nickserv.go
=> implement NS RENAME

irc/accounts.go
=> fix casefolding issue in NS SUSPEND DEL

irc/channel.go
=> fix duplicated JOIN line sent to some resuming clients

irc/help.go
We've gotten two separate reports that this is hard to find.
=> mention UN[DK]LINE in [DK]LINE help

irc/message_cache.go
This is a bug introduced by #1400. Clients like HexChat that support `server-time` and/or `account-tag`, but not `message-tags`, would incorrectly receive relayed `TAGMSG`.
=> fix TAGMSG being relayed to clients without message-tags

irc/import.go
=> validate amode recipients during data import

irc/channelmanager.go, irc/chanserv.go, irc/getters.go
1. Consolidate PURGE and UNPURGE into subcommands
2. Add PURGE LIST
3. PURGE ADD now requires a confirmation code
Fixes #1294
=> Enhancements to CS PURGE

irc/roleplay.go
@Mikaela noticed that these weren't displaying correctly.
=> fix incorrect CTCP ACTION messages sent by roleplay

README.md, docs/MANUAL.md
This doesn't fix #1488, but it mitigates the problem a little until we have a proper end user guide.
=> stopgap documentation update for SASL

default.yaml, docs/MANUAL.md, irc/chanserv.go, irc/client.go, irc/commands.go, irc/config.go, irc/connection_limits/limiter.go, irc/dline.go, irc/flatip/flatip.go, irc/getters.go, irc/handlers.go, irc/help.go, irc/ircconn.go, irc/kline.go, irc/nickserv.go, irc/server.go, irc/uban.go, traditional.yaml
This change is O(mn) in code (m subcommands, n ban types), it's a huge mess.
One non-obvious change: I stopped enforcing KLINEs against loopback (#671 for context).
=> UBAN and some other operator changes (fixes #1447)

irc/dline.go, irc/handlers.go, irc/help.go, irc/server.go, irc/uban.go
Most of the machinery was already in place due to ip-check-script.
=> allow UBAN <ip> REQUIRE-SASL

.travis.yml, Dockerfile, go.mod, irc/config.go, irc/email/dkim.go, irc/import.go, irc/jwt/extjwt.go, irc/languages/languages.go, irc/listeners.go, irc/utils/proxy.go
=> upgrade go to 1.16

docs/MANUAL.md
I don't know why it took me so long to write these up!
=> update the FAQ to cover some controversial issues

docs/MANUAL.md
=> docs/MANUAL.md: add recommendation for proxy timeout

irc/handlers.go
=> Send 477 ERR_NEEDREGGEDNICK when an unregistered user messages a +R user.

go.mod, go.sum, irc/client.go, irc/commands.go, irc/handlers.go, irc/ircconn.go, irc/message_cache.go, irc/monitor.go, irc/responsebuffer.go, irc/services.go, irc/uban.go, vendor/github.com/goshuirc/irc-go/ircmsg/message.go, vendor/github.com/goshuirc/irc-go/ircmsg/tags.go, vendor/github.com/goshuirc/irc-go/ircreader/ircreader.go, vendor/modules.txt
=> bump irc-go again

default.yaml, docs/MANUAL.md, irc/chanserv.go, irc/config.go, irc/mysql/history.go, irc/nickserv.go, irc/uban.go, traditional.yaml
Fixes #875 along with the other named issues.
=> close remaining 2.6 issues

irc/config.go
Brings us into compliance with https://github.com/ircv3/ircv3-specifications/pull/440
=> publish the FORWARD 005 token

irc/client.go
I broke this in #1615 / 0d05ab4ff4249f
=> fix autoreplay of DMs

distrib/docker/run.sh
It worked fine in dev. Fix for issue #1665.
=> Update run.sh to use newly renamed ergo binaries

README.md
=> Update status badges in readme for project rename

default.yaml, traditional.yaml
Also fix some spurious differences (mostly in comments) that had crept in between `default.yaml` and `traditional.yaml`.
=> clarify the semantics of additional-nick-limit

.gitignore, Dockerfile, README.md, distrib/docker/docker-compose.yml, distrib/docker/run.sh
- newer alpine image version and cleanup of dockerfile
- updated docker-compose file to use new image
- remove unneeded command from run.sh
- update ergo dockerhub references
=> update dockerfile and minor changes

distrib/init/rc.ergo
=> Submitting rc.ergo

irc/help.go
Apologies I forgot how to squash these 2 commits before I send this PR. 
Feel free to edit it to your liking. I also I feel like these modes help strings in general need a better usage detail. Thoughts?
=> Help string updates for +f mode

default.yaml, irc/client.go, irc/sno/constants.go, irc/sno/utils_test.go, traditional.yaml
Everything _should_ be satisfactory and in tune  with the previous discussions we've had on my attempts at  #1720
=> DISCONNECT Sno for always-on and/or multiclient

irc/uban.go
=> fix UBAN ADD of masks (k-lines) not killing clients

distrib/systemd/ergo.service, ergo.go, go.mod, go.sum, irc/server.go, vendor/github.com/okzk/sdnotify/LICENSE, vendor/github.com/okzk/sdnotify/README.md, vendor/github.com/okzk/sdnotify/notify.go, vendor/github.com/okzk/sdnotify/notify_linux.go, vendor/github.com/okzk/sdnotify/util.go, vendor/modules.txt
Fixes #1733
Tested this in my VM and it appears to work.
=> support systemd notifications

irc/client.go
May help clarify TLS configuration issues, possibly others too
=> add a debug logline for client read errors

gencapdefs.py, irc/caps/defs.go, irc/commands.go, irc/config.go, irc/handlers.go
Fixes #1740
This will fail irctest. @ProgVal do you have spare cycles to update the test? If you post it in a branch I can go through the upgrade pathway (merge into ergochat/irctest, merge this branch into ergochat/ergo, synchronize to ergochat/ergo's `irctest_stable` branch, then PR back to ProgVal/irctest).
=> update draft/register -> draft/account-registration

default.yaml, irc/accounts.go, irc/email/email.go, irc/errors.go, irc/handlers.go, irc/nickserv.go, irc/smtp/smtp.go, traditional.yaml
=> user visible email errors, email timeouts

irc/handlers.go
for #1725 
```
<< uban list
3>> @time=2021-07-13T23:02:39.408Z :ergo.test NOTICE mogad0n :There are 0 active IP/network ban(s) (DLINEs)
3>> @time=2021-07-13T23:02:39.408Z :ergo.test NOTICE mogad0n :Some IPs may also be prevented from connecting by the connection limiter and/or throttler
3>> @time=2021-07-13T23:02:39.408Z :ergo.test NOTICE mogad0n :There are 0 active ban(s) on nick-user-host masks (KLINEs)
3>> @time=2021-07-13T23:02:39.408Z :ergo.test NOTICE mogad0n :There are 1 active account suspensions.
3>> @time=2021-07-13T23:02:39.408Z :ergo.test NOTICE mogad0n :Account test suspended at Tue, 13 Jul 2021 22:16:06 UTC. Duration: indefinite. No reason given.
4<< uban add mogad0n_!*@*
3>> @time=2021-07-13T23:03:06.209Z :ergo.test NOTICE mogad0n :Successfully added UBAN for …
```
=> add timeCreated to /uban list output

docs/MANUAL.md
=> Document mute extbans

irc/modes.go
matching irctest PR: https://github.com/ProgVal/irctest/pull/95
=> Add missing channel parameter to ERR_INVALIDMODEPARAM.

irc/modes.go
=> fix handling of +k with an empty key parameter

irc/strings.go
Partially fixes #1679, not sure whether to police the relaymsg config or not
=> add # to disfavoredNameCharacters

docs/MANUAL.md
=> document gamja

irc/handlers.go
=> Send snomask for channel mode changes via SAMODE.

languages/README.md
Title and Crowdin link repaired.
Signed-off-by: Georg <georg@lysergic.dev>
=> Languages README.md: Oragono -> Ergo

distrib/SMF/README, distrib/SMF/ergo, distrib/SMF/ergo.xml
Signed-off-by: Georg <georg@lysergic.dev>
=> OpenSolaris / Illumos Service Management Facility (SMF) Service

irc/handlers.go
From discussion with @emersion, this will help with UX if people try to
log into their unverified accounts.
=> add FAIL AUTHENTICATE VERIFICATION_REQUIRED

irc/handlers.go
=> change FAIL AUTHENTICATE VERIFICATION_REQUIRED to be a NOTE

default.yaml
@DanielOaks want this in traditional.yaml as well?
=> make +C (no CTCP) a default channel mode

distrib/anope/anope2json.py, distrib/atheme/atheme2json.py
Also ignore an unrecognized field type in anope
Reported by @tacerus a while back, never got around to testing the changes.
=> anope2json, atheme2json: handle non-UTF8 data

distrib/atheme/atheme2json.py
Import stored certfps from Atheme as well.
=> fix the atheme side of #1864

irc/channel.go
See #1858: this was the intent all along, but I missed this issue.
=> +I should allow unregistered users to join a +R channel

default.yaml, go.mod, go.sum, irc/config.go, irc/flock/flock.go, irc/flock/flock_iface.go, irc/flock/flock_plan9.go, irc/server.go, traditional.yaml, vendor/github.com/gofrs/flock/.gitignore, vendor/github.com/gofrs/flock/.travis.yml, vendor/github.com/gofrs/flock/LICENSE, vendor/github.com/gofrs/flock/README.md, vendor/github.com/gofrs/flock/appveyor.yml, vendor/github.com/gofrs/flock/flock.go, vendor/github.com/gofrs/flock/flock_aix.go, vendor/github.com/gofrs/flock/flock_unix.go, vendor/github.com/gofrs/flock/flock_winapi.go, vendor/github.com/gofrs/flock/flock_windows.go, vendor/modules.txt
Fixes #1823
Still undecided about whether this is a good idea.
=> optionally protect against multiple starts with flock

default.yaml
=> disable languages in default.yaml

irc/nickserv.go
=> add a warning about NS UNREGISTER unregistering channels

docs/MANUAL.md
This has come up a couple of times, probably should be documented.
Not terribly happy with the wording, please feel free to make it better!
=> Add FAQ about WebIRC and secure clients

gencapdefs.py, irc/accounts.go, irc/caps/defs.go, irc/channel.go, irc/client.go, irc/commands.go, irc/getters.go, irc/handlers.go, irc/help.go, irc/server.go, irc/strings.go
https://github.com/ircv3/ircv3-specifications/pull/489
=> implement draft/read-marker capability

irc/server.go
Found thanks to @mitchr in https://github.com/progval/irctest/pull/164
=> Fix implementation of `LIST <n`

irc/caps/constants.go
@progval , sanity check: the only thing I need to do to implement the ratified version is rename the tag, right?
=> bump bot mode spec to ratified version

irc/client.go
Log it at level INFO for parity with connect / connect-ip
=> make quit logging more consistent

docs/MANUAL.md
=> MANUAL.md: clarify appropiate privs for invite

irc/accounts.go, irc/handlers.go, irc/nickserv.go
=> add SAVERIFY command

irc/server.go
See #1593; this enables a client-side implementation of bulk deletion
=> exempt operators from history cutoffs

docs/MANUAL.md, docs/USERGUIDE.md
=> Documentation: add Python3 syntax highlighting, +i/AMODE documentation and add FAQ on AMODE privileges

irc/accounts.go, irc/client.go, irc/getters.go, irc/handlers.go
This is what comes of not testing against a working client implementation...
=> fix critical bugs in draft/read-marker

irc/channel.go, irc/client.go, irc/socket.go
=> replace some utils.Semaphore with (*sync.Mutex).TryLock

gencapdefs.py, irc/caps/defs.go
https://github.com/ircv3/ircv3-specifications/pull/508
=> Use ratified extended-monitor cap name

irc/config.go
Thanks to @emersion for finding this
=> fix CHATHISTORY 005 token name

default.yaml, traditional.yaml
=> document that persistent history is not affected by buffer limits

CHANGELOG.md
Targeting a release of rc1 within the next week (just need to make a decision on #1870 first).
=> draft changelog for v2.11.0-rc1

irc/config.go
https://github.com/ircv3/ircv3-specifications/pull/510
cc @progval
=> publish MSGREFTYPES 005 token

.github/workflows/build.yml, Dockerfile, go.mod
=> upgrade to go 1.20

Makefile, README.md
=> change default make target to `build`

irc/handlers.go
Remove `<no reason supplied>`, make default KILL anonymous
=> tweak KILL message

irc/utils/uuid.go
=> fix linter error

irc/handlers.go
Recommend `/UBAN ADD` instead of the older `/NS SUSPEND`
=> Update response string when killing always on clients

default.yaml, irc/config.go, irc/server.go, traditional.yaml
=> add channel autojoin feature

Dockerfile
=> explicit docker.io in Dockerfile

go.mod, go.sum, vendor/github.com/ergochat/go-ident/client.go, vendor/modules.txt
Fixes a socket leak (that doesn't seem to be affecting tilde.town?)
=> upgrade go-ident

irc/handlers.go
https://github.com/progval/irctest/pull/240
=> Fix typo in ACCOUNT_NAME_MUST_BE_NICK code

.github/workflows/build.yml
Verify that Ergo's CI is compatible with recent irctest changes
=> bump irctest

irc/channel.go, irc/client.go
=> add panic handler to async client/channel writes

.github/workflows/build.yml, Dockerfile, go.mod
No code changes because I didn't really see any API-level stuff in the changelog that was relevant to us: https://go.dev/doc/go1.22
=> upgrade to go 1.22

docs/MANUAL.md
=> add i2pd b32 address directions

irc/getters.go
This fixes #2149 in the master branch.
=> fix deadlock on channel state mutex

CHANGELOG.md, irc/getters.go, irc/version.go
This fixes #2149 in the stable branch.
=> fix #2149 (backport to stable)

.goreleaser.yml, Dockerfile
=> add linux/riscv64 release

gencapdefs.py, irc/caps/constants.go, irc/caps/defs.go, irc/client.go, irc/commands.go, irc/handlers.go, irc/help.go, irc/server.go
https://github.com/ircv3/ircv3-specifications/pull/543
=> implement draft/extended-isupport

default.yaml, irc/client.go, irc/gateways.go, irc/getters.go, irc/nickserv.go, irc/server.go, traditional.yaml
=> add unique connection ID to debug logs

irc/client.go, irc/nickserv.go, irc/services.go
These shouldn't require a second release candidate.
=> tweaks to logging and NS PUSH LIST

irc/config.go
See discussion at https://github.com/ircv3/ircv3-specifications/pull/556
=> add SAFERATE to 005

.goreleaser.yml, default.yaml, docs/API.md, docs/MANUAL.md, ergo.go, irc/api.go, irc/config.go, irc/server.go, traditional.yaml
=> MVP for HTTP API

default.yaml, irc/client.go, irc/commands.go, irc/config.go, traditional.yaml
=> implement command aliases

default.yaml, irc/config.go, irc/roleplay.go, traditional.yaml
See #2229
cc @KlaasT --- could you confirm that this functionality is what you're looking for?
=> allow customizing the NPC and SCENE nickmasks

irc/handlers.go
=> validate that CHATHISTORY limit parameters are nonnegative

irc/handlers.go, irc/nickserv.go
=> Fix invalid FAIL codes in REGISTER
